# Generated by Django 4.2.30 on 2026-04-17 10:00

import core.media
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=220)),
                ('multiple_choice', models.BooleanField(default=False)),
                ('closes_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=140)),
                ('vote_count', models.PositiveIntegerField(default=0)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='posts.poll')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('post_type', models.CharField(choices=[('text', 'Text'), ('photo', 'Photo'), ('video', 'Video'), ('flyer', 'Flyer'), ('story', 'Story'), ('reel', 'Reel'), ('live', 'Live'), ('poll', 'Poll')], db_index=True, default='text', max_length=16)),
                ('title', models.CharField(blank=True, max_length=180)),
                ('caption', models.TextField(blank=True)),
                ('hashtags', models.JSONField(blank=True, default=list)),
                ('mentions', models.JSONField(blank=True, default=list)),
                ('audience', models.CharField(choices=[('public', 'Public'), ('followers', 'Followers'), ('friends', 'Friends'), ('private', 'Private'), ('specific_user', 'Specific user'), ('community', 'Community')], db_index=True, default='public', max_length=20)),
                ('share_target', models.CharField(choices=[('main_feed', 'Main feed'), ('profile', 'Profile'), ('community', 'Community'), ('story', 'Story'), ('reels', 'Reels'), ('live', 'Live')], default='main_feed', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='draft', max_length=16)),
                ('allow_comments', models.BooleanField(default=True)),
                ('allow_sharing', models.BooleanField(default=True)),
                ('save_to_story', models.BooleanField(default=False)),
                ('premium_badge', models.BooleanField(default=False)),
                ('is_sensitive', models.BooleanField(default=False)),
                ('is_edited', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('comment_count', models.PositiveIntegerField(default=0)),
                ('share_count', models.PositiveIntegerField(default=0)),
                ('save_count', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('community', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='communities.community')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PollVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='posts.polloption')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='posts.poll')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_votes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='poll',
            name='post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='poll', to='posts.post'),
        ),
        migrations.CreateModel(
            name='LiveAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_for', models.DateTimeField()),
                ('stream_title', models.CharField(max_length=180)),
                ('access_type', models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('vip', 'VIP'), ('paid', 'Paid')], default='public', max_length=16)),
                ('ticket_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='live_announcement', to='posts.post')),
            ],
        ),
        migrations.CreateModel(
            name='FlyerMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flyer_title', models.CharField(max_length=180)),
                ('body', models.TextField(blank=True)),
                ('call_to_action', models.CharField(blank=True, max_length=120)),
                ('background_style', models.CharField(default='gradient-violet', max_length=80)),
                ('text_color', models.CharField(default='#ffffff', max_length=32)),
                ('layout_style', models.CharField(default='centered', max_length=40)),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flyer_meta', to='posts.post')),
            ],
        ),
        migrations.CreateModel(
            name='PostMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('logo', 'Logo')], max_length=12)),
                ('file', models.FileField(upload_to='posts/media/')),
                ('thumbnail', models.ImageField(blank=True, upload_to='posts/thumbnails/', validators=[core.media.validate_image_file])),
                ('alt_text', models.CharField(blank=True, max_length=180)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('duration', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('display_mode', models.CharField(choices=[('cover', 'Cover'), ('contain', 'Contain'), ('fill', 'Fill')], default='cover', max_length=12)),
                ('crop_style', models.CharField(choices=[('square', 'Square'), ('portrait', 'Portrait'), ('landscape', 'Landscape'), ('story', 'Story'), ('reel', 'Reel')], default='square', max_length=16)),
                ('image_effect', models.CharField(choices=[('none', 'None'), ('warm', 'Warm'), ('cool', 'Cool'), ('cinematic', 'Cinematic'), ('vivid', 'Vivid'), ('bw', 'Black and white')], default='none', max_length=16)),
                ('overlay_text', models.CharField(blank=True, max_length=180)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='posts.post')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
                'indexes': [models.Index(fields=['post', 'sort_order'], name='posts_postm_post_id_30b6bb_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author', 'published_at'], name='posts_post_author__7d9ecb_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['post_type', 'published_at'], name='posts_post_post_ty_260d44_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['audience', 'status'], name='posts_post_audienc_b19ab9_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['status', 'published_at'], name='posts_post_status_384c95_idx'),
        ),
        migrations.AddConstraint(
            model_name='pollvote',
            constraint=models.UniqueConstraint(fields=('user', 'poll'), name='unique_user_poll_vote'),
        ),
    ]
