# Generated by Django 4.2.30 on 2026-04-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_posts_post_author__19d68b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_ai_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='is_public_preview',
            field=models.BooleanField(default=True),
        ),
    ]
