# Generated by Django 4.2.30 on 2026-05-02 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_message_deleted_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stories', '0002_storyitem_is_hidden_by_moderation'),
        ('posts', '0004_post_is_ai_generated_post_is_public_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_hidden_by_moderation',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='action_taken',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='report',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='messaging.message'),
        ),
        migrations.AddField(
            model_name='report',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='report',
            name='staff_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='report',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='stories.storyitem'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['story', 'status', 'created_at'], name='posts_repor_story_i_bbb3cc_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['message', 'status', 'created_at'], name='posts_repor_message_4fe9fd_idx'),
        ),
    ]
