# Generated by Django 4.2.30 on 2026-04-16 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveRoom',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('host_full_name', models.CharField(blank=True, max_length=140)),
                ('host_username', models.CharField(blank=True, max_length=140)),
                ('host_email', models.EmailField(blank=True, max_length=254)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('audience', models.CharField(default='Public', max_length=80)),
                ('room_access', models.CharField(default='Open Room', max_length=80)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('ended', 'Ended')], default='scheduled', max_length=20)),
                ('theme', models.CharField(default='theme-purple', max_length=60)),
                ('quality', models.CharField(default='1280x720', max_length=40)),
                ('frame_rate', models.PositiveIntegerField(default=30)),
                ('view_mode', models.CharField(default='normal', max_length=40)),
                ('allow_gifts', models.BooleanField(default=True)),
                ('allow_comments', models.BooleanField(default=True)),
                ('allow_cohost', models.BooleanField(default=False)),
                ('allow_premium_join', models.BooleanField(default=False)),
                ('allow_premium_view', models.BooleanField(default=False)),
                ('vip_badge', models.BooleanField(default=False)),
                ('private_line', models.BooleanField(default=False)),
                ('location_text', models.CharField(blank=True, max_length=240)),
                ('viewer_count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_live_rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveViewer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=255, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=140)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viewers', to='livestream.liveroom')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-joined_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveGift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_username', models.CharField(blank=True, max_length=140)),
                ('gift_name', models.CharField(max_length=80)),
                ('token_amount', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts', to='livestream.liveroom')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=140)),
                ('username', models.CharField(blank=True, max_length=140)),
                ('message', models.TextField()),
                ('is_host', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='livestream.liveroom')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
