# Generated by Django 4.2.30 on 2026-04-17 11:21

import core.media
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=180, null=True, unique=True)),
                ('sponsor_name', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=12)),
                ('image', models.ImageField(blank=True, upload_to='ads/images/', validators=[core.media.validate_image_file])),
                ('video', models.FileField(blank=True, upload_to='ads/videos/', validators=[core.media.validate_video_file])),
                ('destination_url', models.URLField(blank=True)),
                ('call_to_action', models.CharField(default='Learn more', max_length=80)),
                ('placement', models.CharField(choices=[('homepage_top', 'Homepage top'), ('homepage_mid', 'Homepage mid'), ('homepage_sidebar', 'Homepage sidebar'), ('discover', 'Discover')], db_index=True, default='homepage_mid', max_length=24)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('expired', 'Expired')], db_index=True, default='draft', max_length=16)),
                ('starts_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('priority', models.IntegerField(db_index=True, default=0)),
                ('is_public', models.BooleanField(default=True)),
                ('impression_count', models.PositiveIntegerField(default=0)),
                ('click_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
                'indexes': [models.Index(fields=['placement', 'status', 'starts_at', 'ends_at'], name='ads_adverti_placeme_6143a7_idx'), models.Index(fields=['is_public', 'priority'], name='ads_adverti_is_publ_463d43_idx')],
            },
        ),
    ]
