# Generated by Django 4.2.30 on 2026-04-17 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('text', 'Text'), ('photo', 'Photo'), ('video', 'Video')], default='text', max_length=12)),
                ('file', models.FileField(blank=True, upload_to='stories/')),
                ('text_content', models.TextField(blank=True)),
                ('caption', models.CharField(blank=True, max_length=220)),
                ('background_style', models.CharField(default='midnight', max_length=80)),
                ('text_style', models.CharField(default='clean', max_length=80)),
                ('link_url', models.URLField(blank=True)),
                ('link_label', models.CharField(blank=True, max_length=80)),
                ('audience', models.CharField(choices=[('public', 'Public'), ('followers', 'Followers'), ('friends', 'Friends'), ('private', 'Only me')], db_index=True, default='public', max_length=16)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('comment_count', models.PositiveIntegerField(default=0)),
                ('share_count', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoryComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_comments', to=settings.AUTH_USER_MODEL)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='stories.storyitem')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoryView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='stories.storyitem')),
                ('viewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='story_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['story', 'created_at'], name='stories_sto_story_i_d921fd_idx'), models.Index(fields=['viewer', 'created_at'], name='stories_sto_viewer__f1a03a_idx')],
            },
        ),
        migrations.CreateModel(
            name='StoryShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(default='forward', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='stories.storyitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['story', 'created_at'], name='stories_sto_story_i_e11223_idx'), models.Index(fields=['user', 'created_at'], name='stories_sto_user_id_833bca_idx')],
            },
        ),
        migrations.CreateModel(
            name='StoryReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('like', 'Like'), ('love', 'Love'), ('fire', 'Fire'), ('wow', 'Wow')], default='like', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='stories.storyitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_reactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['story', 'created_at'], name='stories_sto_story_i_807d92_idx'), models.Index(fields=['user', 'created_at'], name='stories_sto_user_id_f7739a_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='storyreaction',
            constraint=models.UniqueConstraint(fields=('story', 'user'), name='unique_story_reaction'),
        ),
        migrations.AddIndex(
            model_name='storyitem',
            index=models.Index(fields=['author', 'created_at'], name='stories_sto_author__6055ab_idx'),
        ),
        migrations.AddIndex(
            model_name='storyitem',
            index=models.Index(fields=['audience', 'expires_at'], name='stories_sto_audienc_d49510_idx'),
        ),
        migrations.AddIndex(
            model_name='storyitem',
            index=models.Index(fields=['expires_at', 'created_at'], name='stories_sto_expires_15516d_idx'),
        ),
        migrations.AddIndex(
            model_name='storycomment',
            index=models.Index(fields=['story', 'created_at'], name='stories_sto_story_i_919a90_idx'),
        ),
        migrations.AddIndex(
            model_name='storycomment',
            index=models.Index(fields=['author', 'created_at'], name='stories_sto_author__fb2770_idx'),
        ),
    ]
