# Generated by Django 4.2.30 on 2026-04-21 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_friendrequest_follow_block_profile_mute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountprofile',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='phone_country_code',
            field=models.CharField(blank=True, default='+264', max_length=8),
        ),
        migrations.AddField(
            model_name='accountprofile',
            name='verification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AccountRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Member'), ('support', 'Support'), ('platform_admin', 'Platform admin'), ('master_admin', 'Master admin')], db_index=True, default='member', max_length=24)),
                ('supabase_uid', models.CharField(blank=True, db_index=True, max_length=64)),
                ('can_manage_promos', models.BooleanField(default=False)),
                ('can_manage_support', models.BooleanField(default=False)),
                ('can_moderate_users', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_role', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['role'], name='accounts_ac_role_5497de_idx'), models.Index(fields=['supabase_uid'], name='accounts_ac_supabas_ac305b_idx')],
            },
        ),
    ]
