# Generated by Django 4.2.30 on 2026-04-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_accountprofile_email_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='region',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name='profile',
            name='town',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['town', 'region'], name='accounts_pr_town_7e4d4e_idx'),
        ),
    ]
