# Generated by Django 4.2.30 on 2026-05-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_hidden_by_moderation',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
