# Generated by Django 4.2.30 on 2026-05-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_is_hidden_by_moderation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('follow', 'New follower'), ('like', 'New like'), ('comment', 'New comment'), ('friend_request', 'Friend request'), ('gift', 'New gift'), ('deposit', 'Deposit status'), ('withdrawal', 'Withdrawal status'), ('message', 'New message'), ('system', 'System update')], max_length=20),
        ),
    ]
