# Generated by Django 4.2.30 on 2026-04-17 17:22

import core.media
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('ended', 'Ended')], db_index=True, default='scheduled', max_length=16)),
                ('thumbnail', models.ImageField(blank=True, upload_to='live/thumbnails/', validators=[core.media.validate_image_file])),
                ('starts_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('access_type', models.CharField(choices=[('public', 'Public'), ('followers', 'Followers'), ('premium', 'Premium'), ('private', 'Private')], db_index=True, default='public', max_length=16)),
                ('stream_key', models.CharField(blank=True, max_length=120)),
                ('playback_url', models.URLField(blank=True)),
                ('chat_enabled', models.BooleanField(default=True)),
                ('viewer_count', models.PositiveIntegerField(default=0)),
                ('peak_viewer_count', models.PositiveIntegerField(default=0)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_featured', '-viewer_count', '-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(choices=[('like', 'Like'), ('love', 'Love'), ('fire', 'Fire'), ('wow', 'Wow')], default='like', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='live.livesession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_reactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LiveModerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('moderator', 'Moderator'), ('producer', 'Producer')], default='moderator', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderators', to='live.livesession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_moderation_roles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LiveMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='live.livesession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveGift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gift_name', models.CharField(max_length=80)),
                ('token_amount', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_gifts_sent', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts', to='live.livesession')),
            ],
        ),
        migrations.CreateModel(
            name='LiveAccessPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_purchases', to='live.livesession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_access_purchases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='livesession',
            index=models.Index(fields=['status', 'starts_at'], name='live_livese_status_cac019_idx'),
        ),
        migrations.AddIndex(
            model_name='livesession',
            index=models.Index(fields=['host', 'status'], name='live_livese_host_id_904bd5_idx'),
        ),
        migrations.AddIndex(
            model_name='livesession',
            index=models.Index(fields=['access_type', 'status'], name='live_livese_access__1c6b59_idx'),
        ),
        migrations.AddIndex(
            model_name='livesession',
            index=models.Index(fields=['is_featured', 'status', 'viewer_count'], name='live_livese_is_feat_25351a_idx'),
        ),
        migrations.AddIndex(
            model_name='livereaction',
            index=models.Index(fields=['session', 'created_at'], name='live_livere_session_f4cd3d_idx'),
        ),
        migrations.AddIndex(
            model_name='livereaction',
            index=models.Index(fields=['user', 'created_at'], name='live_livere_user_id_350340_idx'),
        ),
        migrations.AddConstraint(
            model_name='livereaction',
            constraint=models.UniqueConstraint(fields=('session', 'user'), name='unique_live_reaction'),
        ),
        migrations.AddIndex(
            model_name='livemoderator',
            index=models.Index(fields=['session', 'role'], name='live_livemo_session_c999e0_idx'),
        ),
        migrations.AddConstraint(
            model_name='livemoderator',
            constraint=models.UniqueConstraint(fields=('session', 'user'), name='unique_live_moderator'),
        ),
        migrations.AddIndex(
            model_name='livemessage',
            index=models.Index(fields=['session', 'created_at'], name='live_liveme_session_81edb4_idx'),
        ),
        migrations.AddIndex(
            model_name='livemessage',
            index=models.Index(fields=['user', 'created_at'], name='live_liveme_user_id_0c893b_idx'),
        ),
        migrations.AddIndex(
            model_name='livegift',
            index=models.Index(fields=['session', 'created_at'], name='live_livegi_session_00b738_idx'),
        ),
        migrations.AddIndex(
            model_name='livegift',
            index=models.Index(fields=['sender', 'created_at'], name='live_livegi_sender__b016e5_idx'),
        ),
        migrations.AddIndex(
            model_name='liveaccesspurchase',
            index=models.Index(fields=['session', 'is_active'], name='live_liveac_session_1943ad_idx'),
        ),
        migrations.AddIndex(
            model_name='liveaccesspurchase',
            index=models.Index(fields=['user', 'created_at'], name='live_liveac_user_id_5f9890_idx'),
        ),
        migrations.AddConstraint(
            model_name='liveaccesspurchase',
            constraint=models.UniqueConstraint(fields=('session', 'user'), name='unique_live_access_purchase'),
        ),
    ]
