# Generated by Django 4.2.30 on 2026-04-17 17:05

import core.media
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatingProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=120)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(choices=[('woman', 'Woman'), ('man', 'Man'), ('non_binary', 'Non-binary'), ('other', 'Other')], max_length=20)),
                ('looking_for', models.JSONField(blank=True, default=list)),
                ('bio', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, db_index=True, max_length=100)),
                ('region', models.CharField(blank=True, db_index=True, max_length=100)),
                ('country', models.CharField(default='Namibia', max_length=80)),
                ('occupation', models.CharField(blank=True, max_length=120)),
                ('height_cm', models.PositiveIntegerField(blank=True, null=True)),
                ('interests', models.JSONField(blank=True, default=list)),
                ('relationship_goal', models.CharField(choices=[('serious', 'Serious'), ('dating', 'Dating'), ('friendship', 'Friendship'), ('networking', 'Networking')], db_index=True, default='dating', max_length=20)),
                ('is_visible', models.BooleanField(db_index=True, default=False)),
                ('is_verified_dating', models.BooleanField(default=False)),
                ('show_age', models.BooleanField(default=True)),
                ('show_distance', models.BooleanField(default=True)),
                ('max_distance_km', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dating_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DatingPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_min', models.PositiveIntegerField(default=18)),
                ('age_max', models.PositiveIntegerField(default=60)),
                ('preferred_genders', models.JSONField(blank=True, default=list)),
                ('preferred_region', models.CharField(blank=True, max_length=100)),
                ('preferred_city', models.CharField(blank=True, max_length=100)),
                ('distance_km', models.PositiveIntegerField(blank=True, null=True)),
                ('dating_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='dating.datingprofile')),
            ],
        ),
        migrations.CreateModel(
            name='DatingPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dating/photos/', validators=[core.media.validate_image_file])),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dating_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='dating.datingprofile')),
            ],
            options={
                'ordering': ['-is_primary', 'sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DatingPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dating_passes_sent', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dating_passes_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DatingLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dating_likes_sent', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dating_likes_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('user_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dating_matches_as_one', to=settings.AUTH_USER_MODEL)),
                ('user_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dating_matches_as_two', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user_one', 'is_active'], name='dating_matc_user_on_fadc39_idx'), models.Index(fields=['user_two', 'is_active'], name='dating_matc_user_tw_24add7_idx'), models.Index(fields=['created_at'], name='dating_matc_created_ca51d5_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(fields=('user_one', 'user_two'), name='unique_dating_match_pair'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(check=models.Q(('user_one', models.F('user_two')), _negated=True), name='prevent_self_dating_match'),
        ),
        migrations.AddIndex(
            model_name='datingprofile',
            index=models.Index(fields=['is_visible', 'gender', 'relationship_goal'], name='dating_dati_is_visi_fbd226_idx'),
        ),
        migrations.AddIndex(
            model_name='datingprofile',
            index=models.Index(fields=['city', 'region'], name='dating_dati_city_6e0f13_idx'),
        ),
        migrations.AddIndex(
            model_name='datingprofile',
            index=models.Index(fields=['is_verified_dating', 'created_at'], name='dating_dati_is_veri_1d4ba5_idx'),
        ),
        migrations.AddIndex(
            model_name='datingphoto',
            index=models.Index(fields=['dating_profile', 'is_primary', 'sort_order'], name='dating_dati_dating__ea8ca5_idx'),
        ),
        migrations.AddIndex(
            model_name='datingpass',
            index=models.Index(fields=['from_user', 'created_at'], name='dating_dati_from_us_e96260_idx'),
        ),
        migrations.AddIndex(
            model_name='datingpass',
            index=models.Index(fields=['to_user', 'created_at'], name='dating_dati_to_user_f95b54_idx'),
        ),
        migrations.AddConstraint(
            model_name='datingpass',
            constraint=models.UniqueConstraint(fields=('from_user', 'to_user'), name='unique_dating_pass'),
        ),
        migrations.AddConstraint(
            model_name='datingpass',
            constraint=models.CheckConstraint(check=models.Q(('from_user', models.F('to_user')), _negated=True), name='prevent_self_dating_pass'),
        ),
        migrations.AddIndex(
            model_name='datinglike',
            index=models.Index(fields=['from_user', 'created_at'], name='dating_dati_from_us_f7a072_idx'),
        ),
        migrations.AddIndex(
            model_name='datinglike',
            index=models.Index(fields=['to_user', 'created_at'], name='dating_dati_to_user_926830_idx'),
        ),
        migrations.AddConstraint(
            model_name='datinglike',
            constraint=models.UniqueConstraint(fields=('from_user', 'to_user'), name='unique_dating_like'),
        ),
        migrations.AddConstraint(
            model_name='datinglike',
            constraint=models.CheckConstraint(check=models.Q(('from_user', models.F('to_user')), _negated=True), name='prevent_self_dating_like'),
        ),
    ]
