# Generated by Django 4.2.30 on 2026-04-24 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dating', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatingProfileView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('viewed_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='dating.datingprofile')),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dating_views_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['viewed_profile', 'created_at'], name='dating_dati_viewed__99540c_idx'), models.Index(fields=['viewer', 'created_at'], name='dating_dati_viewer__df7fb1_idx')],
            },
        ),
    ]
