# Generated by Django 4.2.30 on 2026-04-25 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0002_datingprofileview'),
    ]

    operations = [
        migrations.AddField(
            model_name='datingprofile',
            name='boosted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='datingprofile',
            index=models.Index(fields=['boosted_at', 'is_visible'], name='dating_dati_boosted_a175b0_idx'),
        ),
    ]
