# Generated by Django 4.2.30 on 2026-04-25 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def create_existing_coin_balances(apps, schema_editor):
    app_label, model_name = settings.AUTH_USER_MODEL.split(".")
    user_model = apps.get_model(app_label, model_name)
    coin_balance_model = apps.get_model("dating", "DatingCoinBalance")
    for user in user_model.objects.all().only("id"):
        coin_balance_model.objects.get_or_create(user_id=user.id, defaults={"balance": 0})


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dating', '0003_datingprofile_boosted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatingCoinBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='datinglike',
            name='is_super_like',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='datingprofile',
            name='premium_tier',
            field=models.CharField(choices=[('free', 'Free'), ('silver', 'Silver'), ('gold', 'Gold'), ('vip', 'VIP')], db_index=True, default='free', max_length=20),
        ),
        migrations.AddIndex(
            model_name='datinglike',
            index=models.Index(fields=['is_super_like'], name='dating_dati_is_supe_9c5313_idx'),
        ),
        migrations.AddField(
            model_name='datingcoinbalance',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dating_coins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(create_existing_coin_balances, migrations.RunPython.noop),
    ]
