# Generated by Django 4.2.30 on 2026-04-17 17:41

import core.media
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('live', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.ImageField(blank=True, upload_to='wallet/gifts/', validators=[core.media.validate_image_file])),
                ('coin_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('value_to_creator', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['coin_cost', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('billing_period', models.CharField(choices=[('one_time', 'One time'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('feature_flags', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['price', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WalletAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pending_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('lifetime_earned', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('lifetime_spent', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('gift_sent', 'Gift sent'), ('gift_received', 'Gift received'), ('premium_membership_purchase', 'Premium membership purchase'), ('live_access_purchase', 'Live access purchase'), ('creator_payout_credit', 'Creator payout credit'), ('creator_payout_debit', 'Creator payout debit'), ('refund', 'Refund'), ('adjustment', 'Adjustment')], db_index=True, max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('canceled', 'Canceled')], db_index=True, default='pending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='NAD', max_length=8)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=160)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet.walletaccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('canceled', 'Canceled'), ('pending', 'Pending')], db_index=True, default='pending', max_length=20)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('auto_renew', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='wallet.membershipplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-starts_at'],
            },
        ),
        migrations.CreateModel(
            name='GiftEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('creator_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='wallet.giftcatalog')),
                ('live_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_gifts', to='live.livesession')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts_received', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CreatorEntitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entitlement_type', models.CharField(choices=[('live_room', 'Live room'), ('premium_profile', 'Premium profile'), ('premium_post', 'Premium post'), ('replay', 'Replay')], db_index=True, max_length=24)),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_entitlements', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_access_entitlements', to=settings.AUTH_USER_MODEL)),
                ('live_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_entitlements', to='live.livesession')),
                ('source_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entitlements', to='wallet.wallettransaction')),
            ],
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['wallet', 'created_at'], name='wallet_wall_wallet__83a8d3_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['transaction_type', 'created_at'], name='wallet_wall_transac_d6d878_idx'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['status', 'created_at'], name='wallet_wall_status_b6348f_idx'),
        ),
        migrations.AddIndex(
            model_name='usermembership',
            index=models.Index(fields=['user', 'status', 'ends_at'], name='wallet_user_user_id_a376f0_idx'),
        ),
        migrations.AddIndex(
            model_name='usermembership',
            index=models.Index(fields=['plan', 'status'], name='wallet_user_plan_id_2d577a_idx'),
        ),
        migrations.AddIndex(
            model_name='giftevent',
            index=models.Index(fields=['sender', 'created_at'], name='wallet_gift_sender__0ac308_idx'),
        ),
        migrations.AddIndex(
            model_name='giftevent',
            index=models.Index(fields=['recipient', 'created_at'], name='wallet_gift_recipie_0c636d_idx'),
        ),
        migrations.AddIndex(
            model_name='giftevent',
            index=models.Index(fields=['live_session', 'created_at'], name='wallet_gift_live_se_f496e2_idx'),
        ),
        migrations.AddIndex(
            model_name='creatorentitlement',
            index=models.Index(fields=['buyer', 'entitlement_type', 'active'], name='wallet_crea_buyer_i_121e39_idx'),
        ),
        migrations.AddIndex(
            model_name='creatorentitlement',
            index=models.Index(fields=['creator', 'entitlement_type', 'active'], name='wallet_crea_creator_ff48e3_idx'),
        ),
        migrations.AddIndex(
            model_name='creatorentitlement',
            index=models.Index(fields=['live_session', 'active'], name='wallet_crea_live_se_1feed7_idx'),
        ),
    ]
