# Generated by Django 4.2.30 on 2026-05-01 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
        ('posts', '0004_post_is_ai_generated_post_is_public_preview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_notification'),
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('gift_sent', 'Gift sent'), ('gift_received', 'Gift received'), ('boost_purchase', 'Boost purchase'), ('premium_membership_purchase', 'Premium membership purchase'), ('live_access_purchase', 'Live access purchase'), ('creator_payout_credit', 'Creator payout credit'), ('creator_payout_debit', 'Creator payout debit'), ('refund', 'Refund'), ('adjustment', 'Adjustment')], db_index=True, max_length=40),
        ),
        migrations.CreateModel(
            name='BoostCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('post', 'Post'), ('profile', 'Profile'), ('story', 'Story')], db_index=True, max_length=16)),
                ('coin_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('starts_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(db_index=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boost_campaigns', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boost_campaigns', to='posts.post')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boost_campaigns', to='accounts.profile')),
                ('story', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boost_campaigns', to='stories.storyitem')),
            ],
            options={
                'ordering': ['-ends_at', '-created_at'],
                'indexes': [models.Index(fields=['target_type', 'active', 'ends_at'], name='wallet_boos_target__4eb62a_idx'), models.Index(fields=['owner', 'active', 'ends_at'], name='wallet_boos_owner_i_44d8cf_idx'), models.Index(fields=['post', 'active'], name='wallet_boos_post_id_119a81_idx'), models.Index(fields=['profile', 'active'], name='wallet_boos_profile_d362c1_idx'), models.Index(fields=['story', 'active'], name='wallet_boos_story_i_6394d2_idx')],
            },
        ),
    ]
