# Generated by Django 4.2.30 on 2026-05-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_withdrawalrequest_manualdeposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualdeposit',
            name='proof_of_payment',
            field=models.FileField(blank=True, null=True, upload_to='wallet/deposits/proof/'),
        ),
        migrations.AddField(
            model_name='manualdeposit',
            name='user_note',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AlterField(
            model_name='manualdeposit',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid by user'), ('reviewing', 'Admin reviewing'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=16),
        ),
    ]
