from django.urls import path
from .views import (
    add_comment_view,
    author_posts_list_view,
    community_feed_view,
    community_posts_list_view,
    create_post_view,
    delete_post_view,
    delete_comment_view,
    discover_view,
    edit_post_view,
    feed_view,
    following_feed_view,
    friends_feed_view,
    hashtag_view,
    like_post_view,
    nearby_feed_view,
    people_suggestions_view,
    pin_comment_view,
    react_comment_view,
    post_detail_view,
    preview_post_view,
    publish_draft_view,
    reels_feed_view,
    reply_comment_view,
    report_post_view,
    report_user_view,
    save_post_toggle_view,
    search_view,
    save_draft_view,
    save_post_view,
    saved_posts_view,
    share_post_view,
    studio_draft_view,
    studio_view,
    track_post_view,
    trending_feed_view,
    community_suggestions_view,
    media_albums_view,
    media_album_detail_view,
)

urlpatterns = [
    path("", feed_view, name="feed"),
    path("following/", following_feed_view, name="feed_following"),
    path("friends/", friends_feed_view, name="feed_friends"),
    path("trending/", trending_feed_view, name="feed_trending"),
    path("nearby/", nearby_feed_view, name="feed_nearby"),
    path("create/", create_post_view, name="create_post"),
    path("save/", save_post_view, name="save_post"),
    path("studio/", studio_view, name="posts_studio"),
    path("studio/create/", studio_view, name="posts_studio_create"),
    path("studio/draft/", save_draft_view, name="posts_save_draft"),
    path("studio/draft/<uuid:uuid>/", studio_draft_view, name="posts_studio_draft"),
    path("studio/preview/<uuid:uuid>/", preview_post_view, name="posts_preview"),
    path("<uuid:uuid>/", post_detail_view, name="posts_post_detail"),
    path("<uuid:uuid>/edit/", edit_post_view, name="posts_edit_post"),
    path("<uuid:uuid>/delete/", delete_post_view, name="posts_delete_post"),
    path("<uuid:uuid>/publish/", publish_draft_view, name="posts_publish_draft"),
    path("<uuid:uuid>/like/", like_post_view, name="posts_like_post"),
    path("<uuid:uuid>/save-toggle/", save_post_toggle_view, name="posts_save_post_toggle"),
    path("<uuid:uuid>/share/", share_post_view, name="posts_share_post"),
    path("<uuid:uuid>/view/", track_post_view, name="posts_track_post_view"),
    path("<uuid:uuid>/comment/", add_comment_view, name="posts_add_comment"),
    path("<uuid:uuid>/report/", report_post_view, name="posts_report_post"),
    path("comment/<int:id>/reply/", reply_comment_view, name="posts_reply_comment"),
    path("comment/<int:id>/delete/", delete_comment_view, name="posts_delete_comment"),
    path("comment/<int:id>/pin/", pin_comment_view, name="posts_pin_comment"),
    path("author/<str:username>/", author_posts_list_view, name="posts_author_posts"),
    path("community/<slug:slug>/", community_posts_list_view, name="posts_community_posts"),
    path("community/<slug:slug>/feed/", community_feed_view, name="posts_community_feed"),
    path("reels/feed/", reels_feed_view, name="posts_reels_feed"),
    path("discover/", discover_view, name="posts_discover"),
    path("discover/search/", search_view, name="posts_search"),
    path("discover/people/", people_suggestions_view, name="posts_people_suggestions"),
    path("discover/communities/", community_suggestions_view, name="posts_community_suggestions"),
    path("saved/", saved_posts_view, name="posts_saved"),
    path("albums/", media_albums_view, name="posts_albums"),
    path("albums/<str:kind>/", media_album_detail_view, name="posts_album_detail"),
    path("hashtags/<str:tag>/", hashtag_view, name="posts_hashtag"),
    path("profile/<str:username>/report/", report_user_view, name="posts_report_user"),
    path("comment/<int:id>/react/", react_comment_view, name="posts_react_comment"),
]
