ALTER TABLE chain_profiles ADD COLUMN IF NOT EXISTS country TEXT;
ALTER TABLE chain_profiles ADD COLUMN IF NOT EXISTS storage_bucket TEXT;
ALTER TABLE chain_profiles ADD COLUMN IF NOT EXISTS storage_path TEXT;
ALTER TABLE chain_profiles ADD COLUMN IF NOT EXISTS activities JSONB DEFAULT '[]'::jsonb;
ALTER TABLE chain_profiles ADD COLUMN IF NOT EXISTS gender TEXT;
ALTER TABLE chain_profiles ADD COLUMN IF NOT EXISTS relationship_status TEXT;
ALTER TABLE chain_profiles ADD COLUMN IF NOT EXISTS profile_type TEXT DEFAULT 'personal';
ALTER TABLE chain_profiles ADD COLUMN IF NOT EXISTS posts_count INTEGER DEFAULT 0;
ALTER TABLE chain_profiles ADD COLUMN IF NOT EXISTS reels_count INTEGER DEFAULT 0;
ALTER TABLE chain_profiles ADD COLUMN IF NOT EXISTS live_rooms_count INTEGER DEFAULT 0;
ALTER TABLE chain_profiles ADD COLUMN IF NOT EXISTS verified BOOLEAN DEFAULT FALSE;
ALTER TABLE chain_profiles ADD COLUMN IF NOT EXISTS email_verified BOOLEAN DEFAULT FALSE;
ALTER TABLE chain_profiles ADD COLUMN IF NOT EXISTS visibility TEXT DEFAULT 'public';
ALTER TABLE chain_profiles ADD COLUMN IF NOT EXISTS allow_messages BOOLEAN DEFAULT TRUE;
ALTER TABLE chain_profiles ADD COLUMN IF NOT EXISTS allow_dating BOOLEAN DEFAULT TRUE;
ALTER TABLE chain_profiles ADD COLUMN IF NOT EXISTS allow_gifts BOOLEAN DEFAULT TRUE;
ALTER TABLE chain_profiles ADD COLUMN IF NOT EXISTS terms_accepted_at TIMESTAMPTZ;
ALTER TABLE chain_profiles ADD COLUMN IF NOT EXISTS dating_mode_enabled BOOLEAN DEFAULT FALSE;
ALTER TABLE chain_profiles ADD COLUMN IF NOT EXISTS creator_mode_enabled BOOLEAN DEFAULT FALSE;
ALTER TABLE chain_profiles ADD COLUMN IF NOT EXISTS seller_mode_enabled BOOLEAN DEFAULT FALSE;
ALTER TABLE chain_profiles ADD COLUMN IF NOT EXISTS premium_mode_enabled BOOLEAN DEFAULT FALSE;
ALTER TABLE chain_profiles ADD COLUMN IF NOT EXISTS premium_tier TEXT;
ALTER TABLE chain_profiles ADD COLUMN IF NOT EXISTS trust_score INTEGER DEFAULT 0;
ALTER TABLE chain_profiles ADD COLUMN IF NOT EXISTS total_likes INTEGER DEFAULT 0;
ALTER TABLE chain_profiles ADD COLUMN IF NOT EXISTS profile_completion INTEGER DEFAULT 0;
ALTER TABLE chain_profiles ADD COLUMN IF NOT EXISTS website TEXT;
ALTER TABLE chain_profiles ADD COLUMN IF NOT EXISTS pronouns TEXT;
ALTER TABLE chain_profiles ADD COLUMN IF NOT EXISTS skills JSONB DEFAULT '[]'::jsonb;
ALTER TABLE chain_profiles ADD COLUMN IF NOT EXISTS profile_theme TEXT;
ALTER TABLE chain_profiles ADD COLUMN IF NOT EXISTS rank TEXT;
ALTER TABLE chain_profiles ADD COLUMN IF NOT EXISTS chain_score INTEGER DEFAULT 0;
ALTER TABLE chain_profiles ADD COLUMN IF NOT EXISTS portfolio_url TEXT;
ALTER TABLE chain_profiles ADD COLUMN IF NOT EXISTS portfolio_projects JSONB DEFAULT '[]'::jsonb;
ALTER TABLE chain_profiles ADD COLUMN IF NOT EXISTS business_name TEXT;
ALTER TABLE chain_profiles ADD COLUMN IF NOT EXISTS business_website TEXT;
ALTER TABLE chain_profiles ADD COLUMN IF NOT EXISTS business_opening_hours JSONB DEFAULT '{}'::jsonb;
ALTER TABLE chain_profiles ADD COLUMN IF NOT EXISTS business_location_data JSONB DEFAULT '{}'::jsonb;
ALTER TABLE chain_profiles ADD COLUMN IF NOT EXISTS business_services JSONB DEFAULT '[]'::jsonb;
ALTER TABLE chain_profiles ADD COLUMN IF NOT EXISTS business_products JSONB DEFAULT '[]'::jsonb;
ALTER TABLE chain_profiles ADD COLUMN IF NOT EXISTS business_contact_email TEXT;
ALTER TABLE chain_profiles ADD COLUMN IF NOT EXISTS business_contact_phone TEXT;
