#!/usr/bin/env python3
"""
Phase 61 — Creator Economy System
Tests covering SQL, service, API routes, blueprint, template, CSS, JS,
creator levels, analytics, earnings, support, profile upgrade, code quality
"""
import os, sys, json, subprocess, importlib
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
os.environ["FLASK_TESTING"] = "1"
os.environ["CHAIN_FAST_LOCAL"] = "1"

from flask import Flask, session as flask_session

PASS = 0
FAIL = 0
ERRORS = []

def check(desc, condition):
    global PASS, FAIL
    if condition:
        PASS += 1
        print(f"  [PASS] {desc}")
    else:
        FAIL += 1
        ERRORS.append(desc)
        print(f"  [FAIL] {desc}")

def safe_read(path):
    try:
        with open(path) as f: return f.read()
    except Exception: return ""

def create_test_app():
    app = Flask(__name__)
    app.secret_key = "test-secret"
    app.config["TESTING"] = True
    return app

print("=" * 60)
print("Phase 61 — Creator Economy System Tests")
print("=" * 60)

# SECTION 1: SQL schema
print("\n--- SQL schema ---")
sql_content = safe_read("sql/phase61_creator_economy.sql")
check("sql/phase61_creator_economy.sql exists", bool(sql_content))
check("ALTER TABLE chain_profiles ADD COLUMN creator_level", "creator_level" in sql_content)
check("ALTER TABLE chain_profiles ADD COLUMN total_views", "total_views" in sql_content)
check("ALTER TABLE chain_profiles ADD COLUMN total_earnings_cents", "total_earnings_cents" in sql_content)
check("ALTER TABLE chain_profiles ADD COLUMN total_followers", "total_followers" in sql_content)
check("ALTER TABLE chain_profiles ADD COLUMN total_subscribers", "total_subscribers" in sql_content)
check("ALTER TABLE chain_profiles ADD COLUMN total_tips_cents", "total_tips_cents" in sql_content)
check("ALTER TABLE chain_profiles ADD COLUMN total_gifts_cents", "total_gifts_cents" in sql_content)
check("ALTER TABLE chain_profiles ADD COLUMN supporter_count", "supporter_count" in sql_content)
check("ALTER TABLE chain_profiles ADD COLUMN verified_badge", "verified_badge" in sql_content)
check("ALTER TABLE chain_profiles ADD COLUMN earnings_badge", "earnings_badge" in sql_content)
check("CREATE TABLE chain_creator_levels", "CREATE TABLE IF NOT EXISTS chain_creator_levels" in sql_content)
check("Level key PRIMARY KEY", "level_key text PRIMARY KEY" in sql_content)
check("Level has display_name", "display_name" in sql_content)
check("Level has min_earnings_cents", "min_earnings_cents" in sql_content)
check("Level has min_followers", "min_followers" in sql_content)
check("Level has badge_icon", "badge_icon" in sql_content)
check("Level has badge_color", "badge_color" in sql_content)
check("Creator level seeded", "creator" in sql_content and "Verified Creator" in sql_content)
check("Verified creator level seeded", "verified_creator" in sql_content)
check("Premium creator level seeded", "premium_creator" in sql_content)
check("Business creator level seeded", "business_creator" in sql_content)
check("CREATE TABLE chain_creator_stats", "CREATE TABLE IF NOT EXISTS chain_creator_stats" in sql_content)
check("Creator stats has total_views", "total_views" in sql_content and "total_views" in sql_content.split("CREATE TABLE IF NOT EXISTS chain_creator_stats")[1])
check("Creator stats has engagement_rate", "engagement_rate" in sql_content)
check("CREATE TABLE chain_creator_analytics_events", "CREATE TABLE IF NOT EXISTS chain_creator_analytics_events" in sql_content)
check("Analytics events has event_type", "event_type" in sql_content)
check("Analytics events has event_date", "event_date" in sql_content)
check("Analytics events has value", "value" in sql_content)
check("Analytics events unique constraint", "UNIQUE(profile_id, event_type, event_date)" in sql_content)
check("Index creator_analytics_profile_date", "idx_creator_analytics_profile_date" in sql_content)
check("Index creator_analytics_type", "idx_creator_analytics_type" in sql_content)
check("Subscription billing_interval column", "billing_interval" in sql_content)
check("Subscription benefits column", "benefits" in sql_content)
check("Subscription subscriber_count column", "subscriber_count" in sql_content)
check("Paid content visibility column", "visibility" in sql_content)
check("Paid content title column", "title" in sql_content)
check("Paid content description column", "description" in sql_content)
check("CREATE TABLE chain_creator_post_visibility", "chain_creator_post_visibility" in sql_content)
check("Post visibility has min_tier", "min_tier" in sql_content)
check("Post visibility has price_cents", "price_cents" in sql_content)
check("CREATE TABLE chain_creator_profile_upgrades", "chain_creator_profile_upgrades" in sql_content)
check("Profile upgrades has upgrade_type", "upgrade_type" in sql_content)
check("Profile upgrades has previous_level", "previous_level" in sql_content)
check("Profile upgrades has new_level", "new_level" in sql_content)
check("Idempotent IF NOT EXISTS", "IF NOT EXISTS" in sql_content)

# SECTION 2: creator_service.py
print("\n--- Creator Service ---")
svc_content = safe_read("services/creator_service.py")
check("creator_service.py exists", bool(svc_content))
check("get_creator_dashboard_data function", "get_creator_dashboard_data" in svc_content)
check("get_creator_analytics function", "get_creator_analytics" in svc_content)
check("get_creator_earnings_breakdown function", "get_creator_earnings_breakdown" in svc_content)
check("support_creator function", "support_creator" in svc_content)
check("get_creator_profile_upgrade function", "get_creator_profile_upgrade" in svc_content)
check("upgrade_creator_level function", "upgrade_creator_level" in svc_content)
check("record_analytics_event function", "record_analytics_event" in svc_content)
check("CREATOR_LEVELS_ORDER defined", "CREATOR_LEVELS_ORDER" in svc_content)
check("CREATOR_LEVELS_DISPLAY defined", "CREATOR_LEVELS_DISPLAY" in svc_content)
check("4 levels in order", "creator" in svc_content.split("CREATOR_LEVELS_ORDER")[1].split("]")[0])
check("import creator_feature_service", "creator_feature_service" in svc_content)
check("import creator_monetization_service", "creator_monetization_service" in svc_content)
check("import creator_analytics_engine", "creator_analytics_engine" in svc_content)
check("import creator_verification_service", "creator_verification_service" in svc_content)
check("_db_available helper", "_db_available" in svc_content)
check("_uuid helper", "_uuid" in svc_content)
check("_get_profile_basics returns dict", "_get_profile_basics" in svc_content)
check("_get_earnings_breakdown returns dict by type", "_get_earnings_breakdown" in svc_content)
check("_get_analytics_series returns list", "_get_analytics_series" in svc_content)
check("support_creator handles follow", "follow" in svc_content)
check("support_creator handles subscribe", "subscribe" in svc_content)
check("support_creator handles tip", "tip" in svc_content)
check("support_creator handles gift", "gift" in svc_content)
check("Dashboard data includes total_followers", "total_followers" in svc_content)
check("Dashboard data includes total_views", "total_views" in svc_content)
check("Dashboard data includes earnings", "earnings" in svc_content)
check("Dashboard data includes reels_performance", "reels_performance" in svc_content)
check("Dashboard data includes live_performance", "live_performance" in svc_content)
check("Dashboard data includes subscribers", "subscribers" in svc_content)
check("Dashboard data includes tips_cents", "tips_cents" in svc_content)
check("Dashboard data includes gifts_cents", "gifts_cents" in svc_content)
check("Dashboard data includes creator_level", "creator_level" in svc_content)
check("Dashboard data includes verification_status", "verification_status" in svc_content)
check("Analytics returns views series", "views" in svc_content)
check("Analytics returns engagement series", "engagement" in svc_content)
check("Analytics returns follower_growth series", "follower_growth" in svc_content)
check("Analytics returns earnings series", "earnings" in svc_content)
check("Analytics returns summary", "summary" in svc_content)
check("Profile upgrade includes creator_level_display", "creator_level_display" in svc_content)
check("Profile upgrade includes next_level", "next_level" in svc_content)
check("Profile upgrade includes verified_badge", "verified_badge" in svc_content)
check("Profile upgrade includes earnings_badge", "earnings_badge" in svc_content)
check("Profile upgrade includes supporter_count", "supporter_count" in svc_content)
check("Profile upgrade includes subscription_tiers", "subscription_tiers" in svc_content)
check("upgrade_cregor_level returns ok", "ok" in svc_content)

# SECTION 3: API routes
print("\n--- API Routes ---")
routes_content = safe_read("api_routes/creator_routes.py")
check("creator_routes.py exists", bool(routes_content))
check("GET /api/dashboard route", "def api_dashboard" in routes_content)
check("GET /api/analytics route", "def api_analytics" in routes_content)
check("GET /api/earnings route", "def api_earnings" in routes_content)
check("POST /api/support route", "def api_support" in routes_content)
check("GET /api/profile/<profile_id> route", "def api_creator_profile" in routes_content)
check("POST /api/upgrade-level route", "def api_upgrade_level" in routes_content)
check("Dashboard route returns jsonify", "jsonify" in routes_content)
check("Analytics accepts days param", "days" in routes_content)
check("Support checks target_profile_id", "target_profile_id" in routes_content)
check("Support handles action parameter", "action" in routes_content)
check("Profile route handles 'me' alias", "me" in routes_content)
check("Upgrade level accepts target_level", "target_level" in routes_content)
check("Uses creator_bp", "creator_bp" in routes_content)
check("Uses login_required", "login_required" in routes_content)
check("Imports creator_service functions", "from services.creator_service import" in routes_content)
check("Imports creator_feature_service", "from services.creator_feature_service import" in routes_content)
check("Imports creator_analytics_engine", "from services.creator_analytics_engine import" in routes_content)
dash_route = "creator_bp.route('/api/dashboard'" in routes_content or "creator_bp.route(\"/api/dashboard\"" in routes_content
check("/api/dashboard route registered", dash_route)
check("/api/analytics route registered", "api/analytics" in routes_content)
check("/api/earnings route registered", "api/earnings" in routes_content)
check("/api/support route registered", "api/support" in routes_content)
check("/api/profile route registered", "api/profile" in routes_content)
check("/api/upgrade-level route registered", "upgrade-level" in routes_content)
check("Existing /dashboard route preserved", "('/dashboard')" in routes_content or "(\"/dashboard\")" in routes_content)
check("Existing /subscriptions route preserved", "/subscriptions" in routes_content)
check("Existing /paid-posts route preserved", "/paid-posts" in routes_content)
check("Existing /payouts route preserved", "/payouts" in routes_content)
check("Existing /badges route preserved", "/badges" in routes_content)
check("Existing /rankings route preserved", "/rankings" in routes_content)
check("Existing /top-fans route preserved", "/top-fans" in routes_content)
check("Existing /verification/request route preserved", "/verification/request" in routes_content)
check("Existing /sponsorships route preserved", "/sponsorships" in routes_content)
check("Existing /revenue-reports route preserved", "/revenue-reports" in routes_content)

# SECTION 4: Blueprint registration
print("\n--- Blueprint Registration ---")
app_content = safe_read("app.py")
check("creator_bp imported in app.py", "from api_routes.creator_routes import creator_bp" in app_content)
check("creator_bp registered", "app.register_blueprint(creator_bp)" in app_content)

# SECTION 5: Creator levels validation
print("\n--- Creator Levels ---")
check("4 levels defined", len([l for l in ["creator", "verified_creator", "premium_creator", "business_creator"] if l in sql_content]) == 4)
check("Creator is first level", "('creator', 'Creator'" in sql_content.replace(" ", "").replace("\n", "") or "('creator','Creator'" in sql_content.replace(" ", "").replace("\n", ""))
check("Business creator is last level", "business_creator" in sql_content)
check("All levels have badge_icon", "badge_icon" in sql_content)
check("All levels have badge_color", "badge_color" in sql_content)
check("ON CONFLICT DO NOTHING", "ON CONFLICT" in sql_content)

# SECTION 6: Template
print("\n--- Template ---")
tpl_content = safe_read("templates/creator/dashboard.html")
check("Dashboard template exists", bool(tpl_content))
check("Extends base.html", "extends \"base.html\"" in tpl_content or "extends 'base.html'" in tpl_content)
check("CSS link to creator_premium.css", "creator_premium.css" in tpl_content)
check("JS link to creator_premium.js", "creator_premium.js" in tpl_content)
check("Overview tab present", "tab-overview" in tpl_content)
check("Analytics tab present", "tab-analytics" in tpl_content)
check("Earnings tab present", "tab-earnings" in tpl_content)
check("Gifts tab present", "tab-gifts" in tpl_content)
check("Live tab present", "tab-live" in tpl_content)
check("Subscriptions tab present", "tab-subs" in tpl_content)
check("Paid posts tab present", "tab-posts" in tpl_content)
check("Premium content tab present", "tab-premium" in tpl_content)
check("Payouts tab present", "tab-payouts" in tpl_content)
check("Sponsorships tab present", "tab-sponsors" in tpl_content)
check("Top fans tab present", "tab-fans" in tpl_content)
check("Badges tab present", "tab-badges" in tpl_content)
check("Verification tab present", "tab-verify" in tpl_content)
check("Creator Profile tab present", "tab-creator-profile" in tpl_content)
check("Overview cards container", "overviewCards" in tpl_content)
check("Quick stats container", "quickStats" in tpl_content)
check("Earnings breakdown container", "earningsBreakdown" in tpl_content)
check("Analytics container", "analyticsContainer" in tpl_content)
check("Creator profile container", "creatorProfileContainer" in tpl_content)
check("Subscription form with id", "creatorSubTier" in tpl_content)
check("Paid post form with id", "paidPostTitle" in tpl_content)
check("Premium content form", "creator-premium-type" in tpl_content)
check("Payout form", "creator-payout-amount" in tpl_content)
check("Sponsorship form", "creator-sponsor-name" in tpl_content)
check("Badge form", "creator-badge-key" in tpl_content)
check("Apply now button", "Apply Now" in tpl_content)
check("Skeleton loading state", "cr-skeleton" in tpl_content)
check("Empty state for gifts", "cr-empty" in tpl_content)

# SECTION 7: Premium CSS
print("\n--- Premium CSS ---")
css_content = safe_read("static/css/creator_premium.css")
check("creator_premium.css exists", bool(css_content))
check("Card class", ".cr-card" in css_content)
check("Card accent class", ".cr-card-accent" in css_content)
check("Card gold gradient", ".cr-card-gold" in css_content)
check("Card pink gradient", ".cr-card-pink" in css_content)
check("Card cyan gradient", ".cr-card-cyan" in css_content)
check("Card green gradient", ".cr-card-green" in css_content)
check("Card blue gradient", ".cr-card-blue" in css_content)
check("Tab class", ".cr-tab" in css_content)
check("Tab active state", ".cr-tab.active" in css_content)
check("Panel class", ".cr-panel" in css_content)
check("Panel active display", ".cr-panel.active" in css_content)
check("Card label", ".cr-card-label" in css_content)
check("Card value", ".cr-card-value" in css_content)
check("Card sub text", ".cr-card-sub" in css_content)
check("Empty state", ".cr-empty" in css_content)
check("Progress bar", ".cr-progress-bar" in css_content)
check("List styles", ".cr-list" in css_content)
check("Badge classes", ".cr-badge" in css_content)
check("Gold badge", ".cr-badge-gold" in css_content)
check("Green badge", ".cr-badge-green" in css_content)
check("Pink badge", ".cr-badge-pink" in css_content)
check("Blue badge", ".cr-badge-blue" in css_content)
check("Form input", ".cr-input" in css_content)
check("Form row", ".cr-form-row" in css_content)
check("Primary button", ".cr-btn-primary" in css_content)
check("Outline button", ".cr-btn-outline" in css_content)
check("Gold button", ".cr-btn-gold" in css_content)
check("Status dot", ".cr-status-dot" in css_content)
check("Verified status dot", ".cr-status-dot.verified" in css_content)
check("Pending status dot", ".cr-status-dot.pending" in css_content)
check("Section title", ".cr-section-title" in css_content)
check("Stat row", ".cr-stat-row" in css_content)
check("Chart area", ".cr-chart-area" in css_content)
check("Toast notification", ".cr-toast" in css_content)
check("Toast error variant", ".cr-toast.cr-toast-error" in css_content)
check("Skeleton style", ".cr-skeleton" in css_content)
check("Shimmer animation", "@keyframes cr-shimmer" in css_content)
check("Level badge", ".cr-level-badge" in css_content)
check("Creator level badge", ".cr-level-creator" in css_content)
check("Verified creator level badge", ".cr-level-verified_creator" in css_content)
check("Premium creator level badge", ".cr-level-premium_creator" in css_content)
check("Business creator level badge", ".cr-level-business_creator" in css_content)
check("Spinner", ".cr-spinner" in css_content)
check("@keyframes cr-spin", "@keyframes cr-spin" in css_content)
check("Responsive 768px", "@media (max-width: 768px)" in css_content)
check("Responsive 480px", "@media (max-width: 480px)" in css_content)
check("44px touch target on tabs", "min-height: 44px" in css_content)
check("44px touch target on buttons", "min-height: 44px" in css_content)

# SECTION 8: Premium JS
print("\n--- Premium JS ---")
js_content = safe_read("static/js/creator_premium.js")
check("creator_premium.js exists", bool(js_content))
check("IIFE wrapper", "function ()" in js_content)
check("State object", "var S" in js_content or "let S" in js_content or "const S" in js_content)
check("switchTab function", "switchTab" in js_content)
check("onTabClick handler", "onTabClick" in js_content)
check("fetchDashboard function", "fetchDashboard" in js_content)
check("Uses /creator/api/dashboard endpoint", "/creator/api/dashboard" in js_content)
check("renderOverviewCards function", "renderOverviewCards" in js_content)
check("renderQuickStats function", "renderQuickStats" in js_content)
check("renderAnalytics function", "renderAnalytics" in js_content)
check("renderEarnings function", "renderEarnings" in js_content)
check("renderCreatorProfile function", "renderCreatorProfile" in js_content)
check("Fetches /creator/api/profile/me", "/creator/api/profile/me" in js_content)
check("formatCoins helper", "formatCoins" in js_content)
check("esc helper", "esc" in js_content)
check("toast function", "toast" in js_content)
check("creatorPost global function", "creatorPost" in js_content)
check("Tab clicks with event listeners", "tabKey" in js_content)
check("Period button clicks", "period" in js_content)
check("DOMContentLoaded init", "DOMContentLoaded" in js_content)
check("Loader show/hide", "loader" in js_content)
check("Level badge rendering", "cr-level" in js_content)
check("Status dot rendering", "cr-status-dot" in js_content)
check("Error toast on failure", "cr-toast-error" in js_content)
check("Network error handling", "Network error" in js_content)
check("Subscription save button handler", "saveSubBtn" in js_content)
check("Paid post button handler", "createPaidPostBtn" in js_content)

# SECTION 9: Seed script
print("\n--- Seed Script ---")
seed_content = safe_read("scripts/seed_phase60_notifications.py")
check("Phase 60 seed script exists (no phase61 seed needed)", bool(seed_content))

# SECTION 10: Import test
print("\n--- Import Check ---")
try:
    import services.creator_service as _cs
    check("creator_service imports cleanly", True)
except Exception as e:
    check("creator_service imports cleanly", False)
    print(f"       Import error: {e}")

try:
    import api_routes.creator_routes as _cr
    # After import, check that the module has creator_bp
    check("creator_routes imports cleanly", True)
except Exception as e:
    check("creator_routes imports cleanly", False)
    print(f"       Import error: {e}")

# SECTION 11: Compile check
print("\n--- Compile Check ---")
try:
    compile(svc_content, "services/creator_service.py", "exec")
    check("creator_service.py compiles", True)
except SyntaxError as e:
    check("creator_service.py compiles", False)
    print(f"       Syntax error: {e}")

# SECTION 12: Flask integration
print("\n--- Flask Integration ---")
try:
    app = create_test_app()
    from api_routes.creator_routes import creator_bp
    app.register_blueprint(creator_bp)
    check("Blueprint registers in Flask without error", True)
except Exception as e:
    check("Blueprint registers in Flask without error", False)
    print(f"       Error: {e}")

# SECTION 13: Code quality
print("\n--- Code Quality ---")
# Check no hardcoded passwords
check("No hardcoded passwords in routes", "password" not in routes_content.lower() or "password" not in routes_content.split("password"))
check("No hardcoded passwords in service", "password" not in svc_content.lower() or "password" not in svc_content.split("password"))
check("No hardcoded passwords in SQL", "password" not in sql_content.lower() or "password" not in sql_content.split("password"))
check("No secrets in routes", "secret" not in routes_content.lower() or "secret" not in routes_content.split("secret"))
check("No secrets in service", "secret" not in svc_content.lower())
check("No debug prints in routes", "'print'" not in routes_content)
check("No debug prints in service", "'print'" not in svc_content)
# Check error handling
check("Routes use try/except or error returns", "return jsonify" in routes_content)

# SECTION 14: Data shape verification
print("\n--- Data Shape Verification ---")
# Verify dashboard data shape
check("Dashboard data has total_followers field", '"total_followers"' in svc_content)
check("Dashboard data has total_views field", '"total_views"' in svc_content)
check("Dashboard data has earnings.total_cents", '"total_cents"' in svc_content)
check("Dashboard data has earnings.breakdown", '"breakdown"' in svc_content)
check("Dashboard data has reels_performance.views", '"views"' in svc_content)
check("Dashboard data has reels_performance.likes", '"likes"' in svc_content)
check("Dashboard data has reels_performance.engagement_rate", '"engagement_rate"' in svc_content)
check("Dashboard data has live_performance.earnings_cents", '"earnings_cents"' in svc_content)
check("Dashboard data has subscribers count", '"subscribers"' in svc_content)
check("Dashboard data has tips_cents", '"tips_cents"' in svc_content)
check("Dashboard data has gifts_cents", '"gifts_cents"' in svc_content)
check("Dashboard data has creator_level", '"creator_level"' in svc_content)
check("Dashboard data has creator_level_display", '"creator_level_display"' in svc_content)
check("Dashboard data has verification_status", '"verification_status"' in svc_content)
check("Dashboard data has subscriptions.active_count", '"active_count"' in svc_content)
check("Dashboard data has top_supporters", '"top_supporters"' in svc_content)
check("Dashboard data has badges", '"badges"' in svc_content)
# Analytics shape
check("Analytics has views series", '"views"' in svc_content)
check("Analytics has engagement series", '"engagement"' in svc_content)
check("Analytics has follower_growth series", '"follower_growth"' in svc_content)
check("Analytics has earnings series", '"earnings"' in svc_content)
check("Analytics has summary", '"summary"' in svc_content)
check("Analytics summary has total", '"total"' in svc_content)
check("Analytics summary has average", '"average"' in svc_content)
check("Analytics summary has days", '"days"' in svc_content)
# Profile upgrade shape
check("Profile upgrade has profile_id", '"profile_id"' in svc_content)
check("Profile upgrade has username", '"username"' in svc_content)
check("Profile upgrade has creator_level", '"creator_level"' in svc_content)
check("Profile upgrade has next_level", '"next_level"' in svc_content)
check("Profile upgrade has is_verified", '"is_verified"' in svc_content)
check("Profile upgrade has verified_badge", '"verified_badge"' in svc_content)
check("Profile upgrade has earnings_badge", '"earnings_badge"' in svc_content)
check("Profile upgrade has supporter_count", '"supporter_count"' in svc_content)
check("Profile upgrade has verification_status", '"verification_status"' in svc_content)
check("Profile upgrade has badges list", '"badges"' in svc_content)
check("Profile upgrade has subscription_tiers", '"subscription_tiers"' in svc_content)
check("Profile upgrade has total_followers", '"total_followers"' in svc_content)
check("Profile upgrade has total_subscribers", '"total_subscribers"' in svc_content)
check("Profile upgrade has total_earnings_cents", '"total_earnings_cents"' in svc_content)
check("Earnings breakdown has subscriptions", '"subscriptions"' in svc_content)
check("Earnings breakdown has gifts", '"gifts"' in svc_content)
check("Earnings breakdown has tips", '"tips"' in svc_content)
check("Earnings breakdown has content_purchase", '"content_purchase"' in svc_content)

# SECTION 15: Support creator actions
print("\n--- Support Creator ---")
check("support_creator handles 'follow' action", '"follow"' in svc_content)
check("support_creator handles 'subscribe' action", '"subscribe"' in svc_content)
check("support_creator handles 'tip' action", '"tip"' in svc_content)
check("support_creator handles 'gift' action", '"gift"' in svc_content)
check("support_creator validates target_profile_id", "target_profile_id" in svc_content)
check("support_creator returns ok/error", "ok" in svc_content)
check("_follow_creator checks existing follows", "chain_follows" in svc_content)
check("_follow_creator increments total_followers", "total_followers = total_followers + 1" in svc_content)

# Summary
print("\n" + "=" * 60)
print(f"Results: {PASS}/{PASS + FAIL} passed, {FAIL} failed")
print("=" * 60)
if FAIL:
    print("\nFAILED:")
    for e in ERRORS:
        print(f"  - {e}")
    sys.exit(1)
