#!/usr/bin/env python3
"""Phase 62 — Marketplace & Shop Ecosystem Tests."""
import os, sys, json
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
os.environ["FLASK_TESTING"] = "1"
os.environ["CHAIN_FAST_LOCAL"] = "1"

from flask import Flask

PASS = 0
FAIL = 0
ERRORS = []

def check(desc, cond):
    global PASS, FAIL
    if cond:
        PASS += 1
        print(f"  [PASS] {desc}")
    else:
        FAIL += 1
        ERRORS.append(desc)
        print(f"  [FAIL] {desc}")

def safe_read(path):
    try:
        with open(path) as f: return f.read()
    except Exception: return ""

def create_test_app():
    app = Flask(__name__)
    app.secret_key = "test-secret"
    app.config["TESTING"] = True
    return app

print("=" * 60)
print("Phase 62 — Marketplace & Shop Ecosystem Tests")
print("=" * 60)

# SECTION 1: SQL schema
print("\n--- SQL Schema ---")
sql = safe_read("sql/phase62_marketplace.sql")
check("sql/phase62_marketplace.sql exists", bool(sql))
check("CREATE TABLE chain_shops", "CREATE TABLE IF NOT EXISTS chain_shops" in sql)
check("Shops has profile_id FK", "profile_id" in sql.split("chain_shops")[1][:300])
check("Shops has shop_type", "shop_type" in sql)
check("Shops has name", "name" in sql.split("chain_shops")[1][:200])
check("Shops has logo_url", "logo_url" in sql)
check("Shops has banner_url", "banner_url" in sql)
check("Shops has description", "description" in sql)
check("Shops has category", "category" in sql)
check("Shops has contact_email", "contact_email" in sql)
check("Shops has whatsapp", "whatsapp" in sql)
check("Shops has location", "location" in sql)
check("Shops has is_verified", "is_verified" in sql)
check("Shops has followers_count", "followers_count" in sql)
check("Shops has products_count", "products_count" in sql)
check("Shops has services_count", "services_count" in sql)
check("Shops has rating", "rating" in sql)
check("Shops has review_count", "review_count" in sql)
check("Shops has is_active", "is_active" in sql)
check("CREATE TABLE chain_products", "CREATE TABLE IF NOT EXISTS chain_products" in sql)
check("Products has shop_id FK", "shop_id" in sql.split("chain_products")[1][:300])
check("Products has title", "title" in sql.split("chain_products")[1][:200])
check("Products has images array", "images text[]" in sql)
check("Products has price_cents", "price_cents" in sql)
check("Products has stock", "stock" in sql)
check("Products has category", "category" in sql.split("chain_products")[1][:400])
check("Products has condition", "condition" in sql)
check("Products has tags array", "tags text[]" in sql)
check("Products has is_featured", "is_featured" in sql)
check("Products has sales_count", "sales_count" in sql)
check("Products has rating", "rating" in sql)
check("CREATE TABLE chain_services", "CREATE TABLE IF NOT EXISTS chain_services" in sql)
check("Services has hourly_rate_cents", "hourly_rate_cents" in sql)
check("Services has service_area", "service_area" in sql)
check("Services has availability", "availability" in sql)
check("Services has booking_count", "booking_count" in sql)
check("CREATE TABLE chain_bookings", "CREATE TABLE IF NOT EXISTS chain_bookings" in sql)
check("Bookings has client_profile_id", "client_profile_id" in sql)
check("Bookings has provider_profile_id", "provider_profile_id" in sql)
check("Bookings has status", "status" in sql.split("chain_bookings")[1][:500])
check("Bookings has requested_date", "requested_date" in sql)
check("Bookings has scheduled_date", "scheduled_date" in sql)
check("Bookings has completed_date", "completed_date" in sql)
check("Bookings has amount_cents", "amount_cents" in sql)
check("Bookings has is_paid", "is_paid" in sql)
check("CREATE TABLE chain_reviews", "CREATE TABLE IF NOT EXISTS chain_reviews" in sql)
check("Reviews has reviewer_profile_id", "reviewer_profile_id" in sql)
check("Reviews has target_profile_id", "target_profile_id" in sql)
check("Reviews has product_id", "product_id" in sql)
check("Reviews has service_id", "service_id" in sql)
check("Reviews has booking_id", "booking_id" in sql)
check("Reviews has rating CHECK 1-5", "rating" in sql and "CHECK" in sql)
check("Reviews has title", "title" in sql.split("chain_reviews")[1][:600])
check("Reviews has body", "body" in sql)
check("Reviews has image_url", "image_url" in sql)
check("Reviews has is_verified_purchase", "is_verified_purchase" in sql)
check("CREATE TABLE chain_saved_products", "CREATE TABLE IF NOT EXISTS chain_saved_products" in sql)
check("Saved has profile_id", "profile_id" in sql.split("chain_saved_products")[1][:200])
check("Saved has product_id", "product_id" in sql.split("chain_saved_products")[1][:200])
check("Saved has service_id", "service_id" in sql.split("chain_saved_products")[1][:300])
check("Index idx_shops_profile", "idx_shops_profile" in sql)
check("Index idx_shops_category", "idx_shops_category" in sql)
check("Index idx_products_shop", "idx_products_shop" in sql)
check("Index idx_products_category", "idx_products_category" in sql)
check("Index idx_services_shop", "idx_services_shop" in sql)
check("Index idx_bookings_client", "idx_bookings_client" in sql)
check("Index idx_bookings_provider", "idx_bookings_provider" in sql)
check("Index idx_bookings_status", "idx_bookings_status" in sql)
check("Index idx_reviews_reviewer", "idx_reviews_reviewer" in sql)
check("Index idx_reviews_product", "idx_reviews_product" in sql)
check("Index idx_reviews_rating", "idx_reviews_rating" in sql)
check("Index idx_saved_profile", "idx_saved_profile" in sql)
check("Idempotent IF NOT EXISTS", "IF NOT EXISTS" in sql)
check("All CREATE TABLE have IF NOT EXISTS", sql.count("CREATE TABLE") == sql.count("CREATE TABLE IF NOT EXISTS"))

# SECTION 2: Service
print("\n--- Marketplace Shop Service ---")
svc = safe_read("services/marketplace_shop_service.py")
check("marketplace_shop_service.py exists", bool(svc))
check("create_shop function", "def create_shop" in svc)
check("get_shop function", "def get_shop" in svc)
check("get_shop_by_profile function", "def get_shop_by_profile" in svc)
check("update_shop function", "def update_shop" in svc)
check("list_shops function", "def list_shops" in svc)
check("search_shops function", "def search_shops" in svc)
check("create_product function", "def create_product" in svc)
check("get_product function", "def get_product" in svc)
check("list_products function", "def list_products" in svc)
check("search_products function", "def search_products" in svc)
check("save_product function", "def save_product" in svc)
check("unsave_product function", "def unsave_product" in svc)
check("list_saved_products function", "def list_saved_products" in svc)
check("create_service function", "def create_service" in svc)
check("get_service function", "def get_service" in svc)
check("list_services function", "def list_services" in svc)
check("search_services function", "def search_services" in svc)
check("create_booking function", "def create_booking" in svc)
check("get_booking function", "def get_booking" in svc)
check("update_booking_status function", "def update_booking_status" in svc)
check("list_bookings function", "def list_bookings" in svc)
check("create_review function", "def create_review" in svc)
check("list_reviews function", "def list_reviews" in svc)
check("get_seller_dashboard function", "def get_seller_dashboard" in svc)
check("marketplace_search function", "def marketplace_search" in svc)
check("toggle_save function", "def toggle_save" in svc)
check("_db_available helper", "_db_available" in svc)
check("SHOP_TYPES defined", "SHOP_TYPES" in svc)
check("BOOKING_STATUSES defined", "BOOKING_STATUSES" in svc)
check("CATEGORIES_PRODUCT defined", "CATEGORIES_PRODUCT" in svc)
check("CATEGORIES_SERVICE defined", "CATEGORIES_SERVICE" in svc)
check("Product filter by category", "category" in svc and "list_products" in svc[:svc.find("list_products")+300])
check("Product filter by shop_id", "shop_id" in svc.split("def list_products")[1][:300])
check("Product sort newest", "newest" in svc)
check("Product sort trending", "trending" in svc)
check("Service filter by category", "category" in svc.split("def list_services")[1][:300])
check("Search products by query", "title ILIKE" in svc)
check("Search products by min/max price", "min_price" in svc)
check("Booking status PENDING constant", "pending" in svc)
check("Booking status ACCEPTED constant", "accepted" in svc)
check("Booking status REJECTED constant", "rejected" in svc)
check("Booking status COMPLETED constant", "completed" in svc)
check("Review rating validation 1-5", "rating_must_be_1_5" in svc)
check("Review updates aggregates", "_update_review_aggregates" in svc)
check("Review recalculates shop rating", "_recalc_rating" in svc)
check("Dashboard returns shop data", "shop" in svc)
check("Dashboard returns bookings_count", "bookings_count" in svc)
check("Dashboard returns recent_bookings", "recent_bookings" in svc)
check("Dashboard returns total_earnings_cents", "total_earnings_cents" in svc)
check("Search returns products, services, shops", "products" in svc)
check("Search verified_only filter", "verified_only" in svc)
check("Toggle save handles product", "product" in svc.split("def toggle_save")[1][:200])
check("Toggle save handles service", "service_id" in svc.split("def toggle_save")[1][:400])

# SECTION 3: Routes
print("\n--- API Routes ---")
routes = safe_read("api_routes/marketplace_routes.py")
check("marketplace_routes.py exists", bool(routes))
check("GET /marketplace/ route", "marketplace_home" in routes)
check("/marketplace/dashboard route", "marketplace_dashboard" in routes)
check("/marketplace/api/shops route", "api_shops" in routes)
check("/marketplace/api/shops/<shop_id> route", "api_shop_detail" in routes)
check("/marketplace/api/products route", "api_products" in routes)
check("/marketplace/api/products/<product_id> route", "api_product_detail" in routes)
check("/marketplace/api/products/save route", "api_save_product" in routes)
check("/marketplace/api/products/unsave route", "api_unsave_product" in routes)
check("/marketplace/api/services route", "api_services" in routes)
check("/marketplace/api/services/<service_id> route", "api_service_detail" in routes)
check("/marketplace/api/bookings route", "api_bookings" in routes)
check("/marketplace/api/bookings/<id>/status route", "api_booking_status" in routes)
check("/marketplace/api/bookings/<id> detail route", "api_booking_detail" in routes)
check("/marketplace/api/reviews route", "api_reviews" in routes)
check("/marketplace/api/search route", "api_search" in routes)
check("/marketplace/api/saved route", "api_saved" in routes)
check("/marketplace/api/saved/toggle route", "api_toggle_save" in routes)
check("/marketplace/api/dashboard route", "api_dashboard" in routes)
check("Uses marketplace_bp", "marketplace_bp" in routes)
check("Uses login_required", "login_required" in routes)
check("Imports marketplace_shop_service", "from services.marketplace_shop_service import" in routes)
check("Shops returns jsonify", "jsonify" in routes)
check("Products GET accepts category param", "category" in routes.split("def api_products")[1][:300])
check("Products GET accepts sort param", "sort" in routes.split("def api_products")[1][:300])
check("Products GET accepts q param", "q" in routes.split("def api_products")[1][:300])
check("Products POST validates shop_id", "shop_id_and_title_required" in routes)
check("Bookings GET accepts role param", "role" in routes.split("def api_bookings")[1][:200])
check("Bookings PATCH validates booking ownership", "not_authorized" in routes)
check("Reviews GET accepts target_type", "target_type" in routes.split("def api_reviews")[1][:300])
check("Reviews POST validates login", "login_required" in routes)
check("Search accepts q param", "q" in routes.split("def api_search")[1][:200])
check("Search accepts verified_only param", "verified_only" in routes)
check("Saved toggle requires item_id", "item_id_required" in routes)
check("Existing /marketplace/create preserved", "marketplace_create" in routes)
check("Existing /marketplace/my-items preserved", "marketplace_my_items" in routes)
check("Existing /marketplace/item/<id> preserved", "marketplace_detail" in routes)
check("Existing /marketplace/purchase/<id> preserved", "marketplace_purchase" in routes)
check("Existing /marketplace/download/<id> preserved", "marketplace_download" in routes)
check("Existing /music/albums/create preserved", "music_album_create" in routes)
check("Existing /music/tracks/upload preserved", "music_track_upload" in routes)

# SECTION 4: Blueprint
print("\n--- Blueprint Registration ---")
app_content = safe_read("app.py")
check("marketplace_bp imported in app.py", "from api_routes.marketplace_routes import marketplace_bp" in app_content)
check("marketplace_bp registered", "app.register_blueprint(marketplace_bp)" in app_content)

# SECTION 5: Template - index
print("\n--- Template Index ---")
tpl = safe_read("templates/marketplace/index.html")
check("Marketplace index exists", bool(tpl))
check("Extends base.html", "extends \"base.html\"" in tpl or "extends 'base.html'" in tpl)
check("CSS link to marketplace_premium.css", "marketplace_premium.css" in tpl)
check("JS link to marketplace_premium.js", "marketplace_premium.js" in tpl)
check("Products tab", "products" in tpl)
check("Services tab", "services" in tpl)
check("Shops tab", "shops" in tpl)
check("Nearby tab", "nearby" in tpl)
check("Trending tab", "trending" in tpl)
check("Digital tab", "digital" in tpl)
check("Vehicles tab", "vehicles" in tpl)
check("Property tab", "property" in tpl)
check("Jobs tab", "jobs" in tpl)
check("Search bar", "mpSearch" in tpl)
check("Products grid", "mpProductsGrid" in tpl)
check("Services grid", "mpServicesGrid" in tpl)
check("Shops grid", "mpShopsGrid" in tpl)
check("Trending grid", "mpTrendingGrid" in tpl)
check("Skeleton loaders", "mp-skeleton" in tpl)
check("Sentinel for infinite scroll", "mpSentinel" in tpl)
check("Create button", "/marketplace/create" in tpl)
check("Dashboard link", "/marketplace/dashboard" in tpl)
check("Font Awesome included", "font-awesome" in tpl or "fontawesome" in tpl)

# SECTION 6: Template - dashboard
print("\n--- Template Dashboard ---")
dash = safe_read("templates/marketplace/dashboard.html")
check("Marketplace dashboard exists", bool(dash))
check("Dashboard extends base.html", "extends \"base.html\"" in dash or "extends 'base.html'" in dash)
check("Dashboard CSS link", "marketplace_premium.css" in dash)
check("Dashboard JS link", "marketplace_premium.js" in dash)
check("Earnings card", "Earnings" in dash)
check("Products card", "Products" in dash and "products_count" in dash)
check("Services card", "Services" in dash and "services_count" in dash)
check("Bookings card", "Bookings" in dash and "bookings_count" in dash)
check("Recent bookings table", "Recent Bookings" in dash)
check("Booking status badges", "mp-status" in dash)
check("Create shop button", "mpCreateShopBtn" in dash)
check("Create shop form", "mpCreateShopForm" in dash)
check("Shop name input", "mpShopName" in dash)
check("Shop type select", "mpShopType" in dash)
check("Save shop button", "mpSaveShopBtn" in dash)
check("Empty state when no shop", "Create Your Shop" in dash)

# SECTION 7: CSS
print("\n--- Premium CSS ---")
css = safe_read("static/css/marketplace_premium.css")
check("marketplace_premium.css exists", bool(css))
check("Card class", ".mp-card" in css)
check("Card accent", ".mp-card-accent" in css)
check("Card gold", ".mp-card-gold" in css)
check("Card pink", ".mp-card-pink" in css)
check("Card cyan", ".mp-card-cyan" in css)
check("Card green", ".mp-card-green" in css)
check("Item card", ".mp-item-card" in css)
check("Item image", ".mp-item-img" in css)
check("Item title", ".mp-item-title" in css)
check("Item price", ".mp-item-price" in css)
check("Item actions", ".mp-item-actions" in css)
check("Tab class", ".mp-tab" in css)
check("Tab is-active", ".mp-tab.is-active" in css)
check("Panel class", ".mp-panel" in css)
check("Panel is-active", ".mp-panel.is-active" in css)
check("Search bar", ".mp-search-bar" in css)
check("Search input", ".mp-search-input" in css)
check("Button styles", ".mp-btn" in css)
check("Primary button", ".mp-btn-primary" in css)
check("Outline button", ".mp-btn-outline" in css)
check("Gold button", ".mp-btn-gold" in css)
check("Form input", ".mp-input" in css)
check("Form row", ".mp-form-row" in css)
check("Status badges", ".mp-status" in css)
check("Status pending", ".mp-status-pending" in css)
check("Status accepted", ".mp-status-accepted" in css)
check("Status completed", ".mp-status-completed" in css)
check("Status rejected", ".mp-status-rejected" in css)
check("Table styles", ".mp-table" in css)
check("Empty state", ".mp-empty" in css)
check("Skeleton", ".mp-skeleton" in css)
check("Shimmer animation", "@keyframes mp-shimmer" in css)
check("Toast", ".mp-toast" in css)
check("Toast error", ".mp-toast.mp-toast-error" in css)
check("Toast animation", "@keyframes mp-toast-in" in css)
check("Sentinel", ".mp-sentinel" in css)
check("Shop logo", ".mp-shop-logo" in css)
check("Shop header", ".mp-shop-header" in css)
check("Shop stats", ".mp-shop-stats" in css)
check("Grid layouts", ".mp-grid-products" in css)
check("Grid services", ".mp-grid-services" in css)
check("Grid shops", ".mp-grid-shops" in css)
check("Grid 4 columns", ".mp-grid-4" in css)
check("44px touch targets on tabs", "min-height: 44px" in css)
check("44px touch targets on buttons", "min-height: 44px" in css)
check("Responsive 1024px", "@media (max-width: 1024px)" in css)
check("Responsive 768px", "@media (max-width: 768px)" in css)
check("Responsive 480px", "@media (max-width: 480px)" in css)

# SECTION 8: JS
print("\n--- Premium JS ---")
js = safe_read("static/js/marketplace_premium.js")
check("marketplace_premium.js exists", bool(js))
check("IIFE wrapper", "function ()" in js)
check("API endpoints object", "var API" in js or "let API" in js or "const API" in js)
check("State object S", "var S" in js or "let S" in js or "const S" in js)
check("fetchJSON helper", "fetchJSON" in js)
check("postJSON helper", "postJSON" in js)
check("toast function", "toast" in js)
check("esc helper", "esc" in js)
check("renderProduct function", "renderProduct" in js)
check("renderService function", "renderService" in js)
check("renderShop function", "renderShop" in js)
check("loadTab function", "loadTab" in js)
check("switchTab function", "switchTab" in js)
check("initSearch function", "initSearch" in js)
check("initShopForm function", "initShopForm" in js)
check("mpSave global function", "mpSave" in js)
check("DOMContentLoaded init", "DOMContentLoaded" in js)
check("Tab click handler", "switchTab" in js)
check("Loads products tab on init", "loadTab('products')" in js)
check("Loads trending tab on init", "loadTab('trending')" in js)
check("Search API endpoint", "api/search" in js)
check("Shops API endpoint", "api/shops" in js)
check("Products API endpoint", "api/products" in js)
check("Services API endpoint", "api/services" in js)
check("Dashboard API endpoint", "api/dashboard" in js)
check("Search input binding", "mpSearch" in js)
check("Search button binding", "mpSearchBtn" in js)
check("Create shop form handler", "mpCreateShopBtn" in js)
check("Save shop handler", "mpSaveShopBtn" in js)
check("Product save via mpSave", "productId" in js)
check("Toast on save success", "Saved!" in js)
check("Toast on save error", "Already saved" in js)
check("Trending tab shows trending products", "trending" in js)
check("Digital tab shows electronics", "electronics" in js)
check("Empty state for no results", "No results" in js)

# SECTION 9: Seed script
print("\n--- Seed Script ---")
seed = safe_read("scripts/seed_phase62_marketplace.py")
check("seed_phase62_marketplace.py exists", bool(seed))
check("Seed creates shops", "chain_shops" in seed)
check("Seed creates products", "chain_products" in seed)
check("Seed creates services", "chain_services" in seed)
check("3 shops seeded", "SHOP_NAMES" in seed)
check("20 products seeded", "PRODUCTS_DATA" in seed)
check("10 services seeded", "SERVICES_DATA" in seed)
check("Seed handles existing shops", "Shop already exists" in seed)
check("Seed dedup check for products", "SELECT id FROM chain_products WHERE title" in seed)
check("Seed dedup check for services", "SELECT id FROM chain_services WHERE title" in seed)
check("Seed updates products_count", "products_count = products_count + 1" in seed)
check("Seed updates services_count", "services_count = services_count + 1" in seed)

# SECTION 10: Import check
print("\n--- Import Check ---")
try:
    import services.marketplace_shop_service as _ms
    check("marketplace_shop_service imports cleanly", True)
except Exception as e:
    check("marketplace_shop_service imports cleanly", False)
    print(f"  Import error: {e}")

try:
    import api_routes.marketplace_routes as _mr
    check("marketplace_routes imports cleanly", True)
except Exception as e:
    check("marketplace_routes imports cleanly", False)
    print(f"  Import error: {e}")

# SECTION 11: Compile check
print("\n--- Compile Check ---")
try:
    compile(svc, "services/marketplace_shop_service.py", "exec")
    check("marketplace_shop_service.py compiles", True)
except SyntaxError as e:
    check("marketplace_shop_service.py compiles", False)
    print(f"  Syntax error: {e}")

check("marketplace_premium.js has valid syntax", "function" in js and "var API" in js)

# SECTION 12: Flask integration
print("\n--- Flask Integration ---")
try:
    app = create_test_app()
    from api_routes.marketplace_routes import marketplace_bp
    app.register_blueprint(marketplace_bp)
    check("Blueprint registers in Flask without error", True)
except Exception as e:
    check("Blueprint registers in Flask without error", False)
    print(f"  Error: {e}")

# SECTION 13: Code quality
print("\n--- Code Quality ---")
check("No hardcoded passwords in service", "password" not in svc.lower() or "password" not in svc.split("password"))
check("No hardcoded passwords in routes", "password" not in routes.lower() or "password" not in routes.split("password"))
check("No hardcoded passwords in SQL", "password" not in sql.lower() or "password" not in sql.split("password"))
check("No secrets in service", "secret" not in svc.lower())
check("No secrets in routes", "secret" not in routes.lower())
check("No debug prints in service", "'print'" not in svc)
check("No debug prints in routes", "'print'" not in routes)
check("Error handling in routes", "error" in routes.lower())

# SECTION 14: Booking workflow
print("\n--- Booking Workflow ---")
check("Create booking with service_id", "service_id" in svc)
check("Create booking sets status pending", "pending" in svc.split("def create_booking")[1][:600])
check("Update booking can accept", "accepted" in svc)
check("Update booking can reject", "rejected" in svc)
check("Update booking can complete", "completed" in svc)
check("Update booking sets completed_date", "completed_date" in svc)
check("List bookings by client role", "client_profile_id" in svc)
check("List bookings by provider role", "provider_profile_id" in svc)
check("List bookings filters by status", "status" in svc.split("def list_bookings")[1][:300])

# SECTION 15: Reviews workflow
print("\n--- Reviews Workflow ---")
check("Create review validates rating 1-5", "rating_must_be_1_5" in svc)
check("Create review accepts target_profile_id", "target_profile_id" in svc.split("def create_review")[1][:550])
check("Create review accepts shop_id", "shop_id" in svc.split("def create_review")[1][:650])
check("Create review accepts product_id", "product_id" in svc.split("def create_review")[1][:750])
check("Create review accepts service_id", "service_id" in svc.split("def create_review")[1][:850])
check("Create review accepts booking_id", "booking_id" in svc.split("def create_review")[1][:950])
check("Create review accepts image_url", "image_url" in svc.split("def create_review")[1][:1050])
check("Create review handles is_verified_purchase", "is_verified_purchase" in svc.split("def create_review")[1][:1150])
check("List reviews filters by target_type shop", "shop" in svc.split("def list_reviews")[1][:200])
check("List reviews filters by target_type product", "product" in svc.split("def list_reviews")[1][:300])
check("List reviews filters by target_type service", "service" in svc.split("def list_reviews")[1][:400])
check("List reviews filters by target_type profile", "profile" in svc.split("def list_reviews")[1][:500])
check("Review recalculates shop rating", "chain_shops" in svc)
check("Review recalculates product rating", "chain_products" in svc)
check("Review recalculates service rating", "chain_services" in svc)

# SECTION 16: Search functionality
print("\n--- Search ---")
check("marketplace_search returns dict with products", "\"products\"" in svc or "'products'" in svc)
check("marketplace_search returns dict with services", "\"services\"" in svc or "'services'" in svc)
check("marketplace_search returns dict with shops", "\"shops\"" in svc or "'shops'" in svc)
check("Search accepts min/max price", "min_price" in svc and "max_price" in svc)
check("Search accepts location", "location" in svc.split("def marketplace_search")[1][:300])
check("Search verified_only", "verified_only" in svc.split("def marketplace_search")[1][:300])

# SECTION 17: Service data validation
print("\n--- Service Data ---")
check("Service has hourly_rate_cents field", "hourly_rate_cents" in svc)
check("Service has service_area field", "service_area" in svc)
check("Service has availability field", "availability" in svc)
check("Service has booking_count field", "booking_count" in sql)
check("Service has rating field", "rating" in svc)
check("Service has review_count field", "review_count" in svc)
check("Service has is_featured field", "is_featured" in svc)

# SECTION 18: Seller dashboard validation
print("\n--- Seller Dashboard ---")
check("Dashboard returns shop object", "shop" in svc.split("def get_seller_dashboard")[1][:300])
check("Dashboard returns products_count", "products_count" in svc.split("def get_seller_dashboard")[1][:400])
check("Dashboard returns services_count", "services_count" in svc.split("def get_seller_dashboard")[1][:500])
check("Dashboard returns bookings_count", "bookings_count" in svc.split("def get_seller_dashboard")[1][:600])
check("Dashboard returns total_earnings_cents", "total_earnings_cents" in svc.split("def get_seller_dashboard")[1][:700])
check("Dashboard returns followers_count", "followers_count" in svc.split("def get_seller_dashboard")[1][:800])
check("Dashboard returns recent_bookings", "recent_bookings" in svc.split("def get_seller_dashboard")[1][:900])
check("Dashboard queries products count", "COUNT" in svc.split("def get_seller_dashboard")[1])
check("Dashboard queries bookings sum", "SUM" in svc.split("def get_seller_dashboard")[1])

# Summary
print("\n" + "=" * 60)
print(f"Results: {PASS}/{PASS + FAIL} passed, {FAIL} failed")
print("=" * 60)
if FAIL:
    print("\nFAILED:")
    for e in ERRORS:
        print(f"  - {e}")
    sys.exit(1)
