#!/usr/bin/env python3
"""Phase 63 — Premium Dating System Tests."""
import os, sys, json
sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
os.environ["FLASK_TESTING"] = "1"
os.environ["CHAIN_FAST_LOCAL"] = "1"

from flask import Flask

PASS = 0
FAIL = 0
ERRORS = []

def check(desc, cond):
    global PASS, FAIL
    if cond:
        PASS += 1
        print(f"  [PASS] {desc}")
    else:
        FAIL += 1
        ERRORS.append(desc)
        print(f"  [FAIL] {desc}")

def safe_read(path):
    try:
        with open(path) as f: return f.read()
    except Exception: return ""

def create_test_app():
    app = Flask(__name__)
    app.secret_key = "test-secret"
    app.config["TESTING"] = True
    return app

print("=" * 60)
print("Phase 63 — Premium Dating System Tests")
print("=" * 60)

# SECTION 1: SQL schema
print("\n--- SQL Schema ---")
sql = safe_read("sql/phase63_dating.sql")
check("sql/phase63_dating.sql exists", bool(sql))
check("CREATE TABLE chain_dating_profiles", "CREATE TABLE IF NOT EXISTS chain_dating_profiles" in sql)
check("Dating profiles has profile_id", "profile_id" in sql.split("chain_dating_profiles")[1][:300])
check("Dating profiles has dating_mode_on", "dating_mode_on" in sql)
check("Dating profiles has relationship_goal", "relationship_goal" in sql)
check("Dating profiles has age_range_min", "age_range_min" in sql)
check("Dating profiles has age_range_max", "age_range_max" in sql)
check("Dating profiles has location_preference", "location_preference" in sql)
check("Dating profiles has bio", "bio" in sql.split("chain_dating_profiles")[1][:500])
check("Dating profiles has interests array", "interests text[]" in sql)
check("Dating profiles has photos array", "photos text[]" in sql)
check("Dating profiles has verification_status", "verification_status" in sql)
check("Dating profiles has trust_score", "trust_score" in sql)
check("Dating profiles has safety_badge", "safety_badge" in sql)
check("Dating profiles has hide_from_contacts", "hide_from_contacts" in sql)
check("Dating profiles has visible_to_verified_only", "visible_to_verified_only" in sql)
check("CREATE TABLE chain_dating_likes", "CREATE TABLE IF NOT EXISTS chain_dating_likes" in sql)
check("Likes has actor_profile_id", "actor_profile_id" in sql.split("chain_dating_likes")[1][:300])
check("Likes has target_profile_id", "target_profile_id" in sql)
check("Likes has action_type", "action_type" in sql)
check("Likes has is_mutual", "is_mutual" in sql)
check("CREATE TABLE chain_dating_matches", "CREATE TABLE IF NOT EXISTS chain_dating_matches" in sql)
check("Matches has profile_id_a", "profile_id_a" in sql.split("chain_dating_matches")[1][:200])
check("Matches has profile_id_b", "profile_id_b" in sql)
check("Matches has compatibility_score", "compatibility_score" in sql)
check("Matches has is_active", "is_active" in sql)
check("CREATE TABLE chain_dating_reports", "CREATE TABLE IF NOT EXISTS chain_dating_reports" in sql)
check("Reports has reporter_profile_id", "reporter_profile_id" in sql.split("chain_dating_reports")[1][:200])
check("Reports has reported_profile_id", "reported_profile_id" in sql)
check("Reports has reason", "reason" in sql)
check("Reports has details", "details" in sql)
check("Reports has is_resolved", "is_resolved" in sql)
check("CREATE TABLE chain_dating_blocks", "CREATE TABLE IF NOT EXISTS chain_dating_blocks" in sql)
check("Blocks has blocker_profile_id", "blocker_profile_id" in sql.split("chain_dating_blocks")[1][:200])
check("Blocks has blocked_profile_id", "blocked_profile_id" in sql)
check("CREATE TABLE chain_dating_preferences", "CREATE TABLE IF NOT EXISTS chain_dating_preferences" in sql)
check("Preferences has profile_id", "profile_id" in sql.split("chain_dating_preferences")[1][:200])
check("Preferences has interested_in", "interested_in" in sql)
check("Preferences has min_age", "min_age" in sql)
check("Preferences has max_age", "max_age" in sql)
check("Preferences has max_distance_km", "max_distance_km" in sql)
check("Preferences has show_me", "show_me" in sql)
check("Preferences has only_verified", "only_verified" in sql)
check("Preferences has hide_from_contacts", "hide_from_contacts" in sql.split("chain_dating_preferences")[1][:400])
check("Index idx_dating_profiles_profile", "idx_dating_profiles_profile" in sql)
check("Index idx_dating_likes_actor", "idx_dating_likes_actor" in sql)
check("Index idx_dating_matches_pair", "idx_dating_matches_pair" in sql)
check("Index idx_dating_blocks_pair", "idx_dating_blocks_pair" in sql)
check("Index idx_dating_reports_reporter", "idx_dating_reports_reporter" in sql)
check("Index idx_dating_preferences_profile", "idx_dating_preferences_profile" in sql)
check("Idempotent IF NOT EXISTS on all CREATE TABLE", sql.count("CREATE TABLE") == sql.count("CREATE TABLE IF NOT EXISTS"))

# SECTION 2: Service
print("\n--- Dating Service ---")
svc = safe_read("services/dating_service.py")
check("dating_service.py exists", bool(svc))
check("get_dating_profile function", "def get_dating_profile" in svc)
check("get_or_create_dating_profile function", "def get_or_create_dating_profile" in svc)
check("update_dating_profile function", "def update_dating_profile" in svc)
check("set_dating_mode function", "def set_dating_mode" in svc)
check("get_discover_profiles function", "def get_discover_profiles" in svc)
check("like_profile function", "def like_profile" in svc)
check("pass_profile function", "def pass_profile" in svc)
check("super_like_profile function", "def super_like_profile" in svc)
check("undo_last_action function", "def undo_last_action" in svc)
check("get_matches function", "def get_matches" in svc)
check("get_likes_you function", "def get_likes_you" in svc)
check("block_user function", "def block_user" in svc)
check("report_user function", "def report_user" in svc)
check("get_dating_preferences function", "def get_dating_preferences" in svc)
check("update_dating_preferences function", "def update_dating_preferences" in svc)
check("calculate_compatibility function", "def calculate_compatibility" in svc)
check("restrict_dating_visibility function", "def restrict_dating_visibility" in svc)
check("_db_available helper", "_db_available" in svc)
check("RELATIONSHIP_GOALS constant", "RELATIONSHIP_GOALS" in svc)
check("ACTION_TYPES constant", "ACTION_TYPES" in svc)
check("REPORT_REASONS constant", "REPORT_REASONS" in svc)
check("set_dating_preferences alias", "set_dating_preferences" in svc)
check("Likes has unique constraint handling", "already_interacted" in svc)
check("Super like triggers mutual match", "is_match" in svc)
check("Mutual match logic in _record_action", "is_match" in svc.split("def _record_action")[1])
check("Match inserts into chain_dating_matches", "INSERT INTO chain_dating_matches" in svc)
check("Block deletes matches", "DELETE FROM chain_dating_matches" in svc)
check("Block deletes likes", "DELETE FROM chain_dating_likes" in svc)
check("Report inserts into chain_dating_reports", "INSERT INTO chain_dating_reports" in svc)
check("Cannot interact with self", "cannot_interact_with_self" in svc)
check("Cannot block self", "cannot_block_self" in svc)
check("Cannot report self", "cannot_report_self" in svc)
check("Already blocked check", "already_blocked" in svc)
check("Already interacted check", "already_interacted" in svc)
check("Compatibility by interests", "a_interests" in svc)
check("Compatibility by goal", "relationship_goal" in svc.split("def calculate_compatibility")[1])
check("Compatibility by location", "location_preference" in svc.split("def calculate_compatibility")[1])
check("Compatibility by trust score", "trust_score" in svc.split("def calculate_compatibility")[1])
check("Compatibility capped at 100", "min(100" in svc)
check("Compatibility floors at 0", "max(0" in svc)
check("Discover filters blocked", "_get_blocked_ids" in svc)
check("Discover excludes dating_mode_off", "dating_mode_on = true" in svc)
check("Get matches queries both sides", "profile_id_a = %s OR m.profile_id_b = %s" in svc or "m.profile_id_a" in svc)
check("Likes you filters is_mutual false", "is_mutual = false" in svc)
check("is_blocked function", "def is_blocked" in svc)
check("is_blocked_by function", "def is_blocked_by" in svc)
check("Undo deletes like", "DELETE FROM chain_dating_likes" in svc.split("def undo_last_action")[1])
check("Undo deletes match", "DELETE FROM chain_dating_matches" in svc.split("def undo_last_action")[1])
check("Restrict visibility function", "hide_from_contacts" in svc.split("def restrict_dating_visibility")[1][:200])

# SECTION 3: Routes
print("\n--- API Routes ---")
routes = safe_read("api_routes/dating_routes.py")
check("dating_routes.py exists", bool(routes))
check("GET /dating/ route", "dating_home" in routes)
check("/dating/discover route", "discover" in routes and "/dating/discover" not in routes.split("dating_home")[0])
check("/dating/profile/<profile_id> route", "dating_profile" in routes)
check("/dating/api/discover route", "api_discover" in routes)
check("/dating/api/like route", "api_like" in routes)
check("/dating/api/pass route", "api_pass" in routes)
check("/dating/api/super-like route", "api_super_like" in routes)
check("/dating/api/undo route", "api_undo" in routes)
check("/dating/api/matches route", "api_matches" in routes)
check("/dating/api/likes-you route", "api_likes_you" in routes)
check("/dating/api/block route", "api_block" in routes)
check("/dating/api/report route", "api_report" in routes)
check("/dating/api/preferences route", "api_preferences" in routes)
check("/dating/api/mode route", "api_mode" in routes)
check("/dating/api/compatibility/<target_id> route", "api_compatibility" in routes)
check("/dating/api/profile route", "api_dating_profile" in routes)
check("/dating/api/restrict route", "api_restrict" in routes)
check("Uses dating_bp", "dating_bp" in routes)
check("Uses login_required", "login_required" in routes)
check("Imports dating_service", "from services.dating_service import" in routes)
check("Like validates target_id", "target_id_required" in routes)
check("Pass validates target_id", "target_id_required" in routes)
check("Super like validates target_id", "target_id_required" in routes)
check("Block validates target_id", "target_id_required" in routes)
check("Report validates target_id", "target_id_required" in routes)
check("Report validates reason", "reason_required" in routes)
check("Preferences GET returns json", "jsonify" in routes)
check("Mode route toggles setting", "set_dating_mode" in routes)
check("Restrict route calls restrict function", "restrict_dating_visibility" in routes)
check("Compatibility returns score", "compatibility_score" in routes.split("def api_compatibility")[1][:200])

# SECTION 4: Blueprint in app.py
print("\n--- Blueprint Registration ---")
app_content = safe_read("app.py")
check("dating_bp imported in app.py", "from api_routes.dating_routes import dating_bp" in app_content)
check("dating_bp registered in app.py", "app.register_blueprint(dating_bp)" in app_content)
check("dating_bp in protected_blueprints", '"dating"' in app_content.split("protected_blueprints")[1][:100])

# SECTION 5: Template
print("\n--- Template ---")
tpl = safe_read("templates/dating/index.html")
check("Dating index exists", bool(tpl))
check("Extends base.html", "extends \"base.html\"" in tpl or "extends 'base.html'" in tpl)
check("CSS link to dating_premium.css", "dating_premium.css" in tpl)
check("JS link to dating_premium.js", "dating_premium.js" in tpl)
check("Discover tab", "discover" in tpl)
check("Matches tab", "matches" in tpl)
check("Likes You tab", "likes-you" in tpl)
check("Messages tab", "messages" in tpl)
check("Verified tab", "verified" in tpl)
check("Nearby tab", "nearby" in tpl)
check("Safety tab", "safety" in tpl)
check("Card stack", "dtCardStack" in tpl)
check("Empty state discover", "dtDiscoverEmpty" in tpl)
check("Empty state matches", "dtMatchesEmpty" in tpl)
check("Empty state likes", "dtLikesEmpty" in tpl)
check("Like button", "dtBtnLike" in tpl)
check("Pass button", "dtBtnPass" in tpl)
check("Super like button", "dtBtnSuper" in tpl)
check("Mode toggle", "dtModeToggle" in tpl)
check("Safety mode toggle", "dtSafetyMode" in tpl)
check("Hide from contacts", "dtHideContacts" in tpl)
check("Verified only", "dtVerifiedOnly" in tpl)
check("Report form", "dtReportBtn" in tpl)
check("Block form", "dtBlockBtn" in tpl)
check("Trust bar", "dtTrustFill" in tpl)
check("Safety badge status", "dtSafetyBadgeStatus" in tpl)
check("Match overlay", "dtMatchOverlay" in tpl)
check("Match celebration", "dtMatchName" in tpl)
check("Match chat button", "dtMatchChat" in tpl)
check("Font Awesome included", "font-awesome" in tpl or "fontawesome" in tpl)

# SECTION 6: CSS
print("\n--- Premium CSS ---")
css = safe_read("static/css/dating_premium.css")
check("dating_premium.css exists", bool(css))
check("Root variables", ":root" in css)
check("Wrap class", ".dt-wrap" in css)
check("Header", ".dt-header" in css)
check("Kicker", ".dt-kicker" in css)
check("Title", ".dt-title" in css)
check("Tabs", ".dt-tabs" in css)
check("Tab is-active", ".dt-tab.is-active" in css)
check("Panel class", ".dt-panel" in css)
check("Panel is-active", ".dt-panel.is-active" in css)
check("Card stack", ".dt-card-stack" in css)
check("Card class", ".dt-card" in css)
check("Card photo", ".dt-card-photo" in css)
check("Compat badge", ".dt-compat-badge" in css)
check("Verified badge", ".dt-verified-badge" in css)
check("Card body", ".dt-card-body" in css)
check("Card interests", ".dt-card-interests" in css)
check("Actions", ".dt-actions" in css)
check("Circle buttons", ".dt-circle" in css)
check("Circle nope", ".dt-circle-nope" in css)
check("Circle super", ".dt-circle-super" in css)
check("Circle like", ".dt-circle-like" in css)
check("Grid", ".dt-grid" in css)
check("Grid card", ".dt-grid-card" in css)
check("Empty state", ".dt-empty" in css)
check("Section card", ".dt-section-card" in css)
check("Muted text", ".dt-muted" in css)
check("Toggle class", ".dt-toggle" in css)
check("Toggle slider", ".dt-toggle-slider" in css)
check("Input", ".dt-input" in css)
check("Form row", ".dt-form-row" in css)
check("Trust bar", ".dt-trust-bar" in css)
check("Trust fill", ".dt-trust-fill" in css)
check("Badge small", ".dt-badge-sm" in css)
check("Match overlay", ".dt-match-overlay" in css)
check("Match modal", ".dt-match-modal" in css)
check("Match icon", ".dt-match-icon" in css)
check("Skeleton", ".dt-skeleton" in css)
check("Shimmer animation", "@keyframes dtShimmer" in css)
check("Toast", ".dt-toast" in css)
check("Toast error", ".dt-toast-error" in css)
check("Toast animation", "@keyframes dtToastIn" in css)
check("Primary button", ".dt-btn-primary" in css)
check("Ghost button", ".dt-btn-ghost" in css)
check("Danger button", ".dt-btn-danger" in css)
check("44px min-height on tabs", "min-height: 44px" in css and ".dt-tab" in css)
check("44px min-height on buttons", "min-height: 44px" in css and ".dt-btn" in css)
check("60px min-height on circles", "min-height: 60px" in css and ".dt-circle" in css)
check("Responsive 1024px", "@media (max-width: 1024px)" in css)
check("Responsive 768px", "@media (max-width: 768px)" in css)
check("Responsive 480px", "@media (max-width: 480px)" in css)

# SECTION 7: JS
print("\n--- Premium JS ---")
js = safe_read("static/js/dating_premium.js")
check("dating_premium.js exists", bool(js))
check("IIFE wrapper", "function ()" in js)
check("API object", "var API" in js or "let API" in js or "const API" in js)
check("State object S", "var S" in js or "let S" in js or "const S" in js)
check("fetchJSON helper", "fetchJSON" in js)
check("postJSON helper", "postJSON" in js)
check("toast function", "toast" in js)
check("esc helper", "esc" in js)
check("renderProfileCard function", "renderProfileCard" in js)
check("renderGridCard function", "renderGridCard" in js)
check("loadDiscover function", "loadDiscover" in js)
check("loadMatches function", "loadMatches" in js)
check("loadLikesYou function", "loadLikesYou" in js)
check("loadSafety function", "loadSafety" in js)
check("switchTab function", "switchTab" in js)
check("swipeLike function", "swipeLike" in js)
check("swipePass function", "swipePass" in js)
check("swipeSuperLike function", "swipeSuperLike" in js)
check("animateCard function", "animateCard" in js)
check("showMatchOverlay function", "showMatchOverlay" in js)
check("undoAction function", "undoAction" in js)
check("initModeToggle function", "initModeToggle" in js)
check("initSafetyControls function", "initSafetyControls" in js)
check("init function", "function init" in js)
check("DOMContentLoaded init", "DOMContentLoaded" in js)
check("Discover API endpoint", "api/discover" in js)
check("Like API endpoint", "api/like" in js)
check("Pass API endpoint", "api/pass" in js)
check("Super like API endpoint", "api/super-like" in js)
check("Matches API endpoint", "api/matches" in js)
check("Likes you API endpoint", "api/likes-you" in js)
check("Block API endpoint", "api/block" in js)
check("Report API endpoint", "api/report" in js)
check("Mode API endpoint", "api/mode" in js)
check("Restrict API endpoint", "api/restrict" in js)
check("Like button binding", "dtBtnLike" in js)
check("Pass button binding", "dtBtnPass" in js)
check("Super like button binding", "dtBtnSuper" in js)
check("Report button binding", "dtReportBtn" in js)
check("Block button binding", "dtBlockBtn" in js)
check("Tab click handler", "data-tab" in js)
check("Match overlay on match", "showMatchOverlay" in js)
check("Toast on success", "success" in js)
check("Toast on error", "error" in js)

# SECTION 8: Seed script
print("\n--- Seed Script ---")
seed = safe_read("scripts/seed_phase63_dating.py")
check("seed_phase63_dating.py exists", bool(seed))
check("5 seed profiles", "chain_star" in seed and "chain_moon" in seed and "chain_gold" in seed and "chain_million" in seed and "chain_premium" in seed)
check("DATING_PROFILES list", "DATING_PROFILES" in seed)
check("Seed inserts into chain_dating_profiles", "INSERT INTO chain_dating_profiles" in seed)
check("Seed inserts into chain_dating_preferences", "INSERT INTO chain_dating_preferences" in seed)
check("Seed handles existing profiles", "Dating profile already exists" in seed)
check("Seed handles missing profiles", "Need at least 2 seeded profiles" in seed)

# SECTION 9: Import check
print("\n--- Import Check ---")
try:
    import services.dating_service as _ds
    check("dating_service imports cleanly", True)
except Exception as e:
    check("dating_service imports cleanly", False)
    print(f"  Import error: {e}")

try:
    import api_routes.dating_routes as _dr
    check("dating_routes imports cleanly", True)
except Exception as e:
    check("dating_routes imports cleanly", False)
    print(f"  Import error: {e}")

# SECTION 10: Compile check
print("\n--- Compile Check ---")
try:
    compile(svc, "services/dating_service.py", "exec")
    check("dating_service.py compiles", True)
except SyntaxError as e:
    check("dating_service.py compiles", False)
    print(f"  Syntax error: {e}")

try:
    compile(routes, "api_routes/dating_routes.py", "exec")
    check("dating_routes.py compiles", True)
except SyntaxError as e:
    check("dating_routes.py compiles", False)
    print(f"  Syntax error: {e}")

check("dating_premium.js has valid syntax", "function" in js and "var API" in js)

# SECTION 11: Flask integration
print("\n--- Flask Integration ---")
try:
    app = create_test_app()
    from api_routes.dating_routes import dating_bp
    app.register_blueprint(dating_bp)
    check("Blueprint registers in Flask without error", True)
except Exception as e:
    check("Blueprint registers in Flask without error", False)
    print(f"  Error: {e}")

# SECTION 12: Mutual match
print("\n--- Mutual Match ---")
check("Like triggers match check", "reciprocal" in svc)
check("Match inserts both directions", "INSERT INTO chain_dating_matches" in svc)
check("Match sets is_mutual on both", "is_mutual = true" in svc)
check("Match returns is_match flag", "is_match" in svc.split("def _record_action")[1])

# SECTION 13: Safety
print("\n--- Safety ---")
check("Report function takes reason", "reason" in svc.split("def report_user")[1][:200])
check("Report function takes details", "details" in svc.split("def report_user")[1][:300])
check("Block deletes matches", "DELETE FROM chain_dating_matches" in svc.split("def block_user")[1])
check("Block deletes likes", "DELETE FROM chain_dating_likes" in svc.split("def block_user")[1])
check("Restrict visibility sets hide_from_contacts", "hide_from_contacts" in svc)
check("Restrict visibility sets visible_to_verified_only", "visible_to_verified_only" in svc)
check("Dating mode off means excluded from discover", "dating_mode_on = true" in svc.split("def get_discover_profiles")[1])
check("Safety badge in dating profile", "safety_badge" in svc)
check("Trust score in dating profile", "trust_score" in svc)
check("Verification status in dating profile", "verification_status" in svc)
check("Hide from contacts in dating profile", "hide_from_contacts" in svc.split("def update_dating_profile")[1])
check("Visible to verified only in dating profile", "visible_to_verified_only" in svc.split("def update_dating_profile")[1])

# SECTION 14: Compatibility
print("\n--- Compatibility ---")
check("Compatibility based on interests", "a_interests" in svc)
check("Compatibility based on relationship goal", "relationship_goal" in svc.split("def calculate_compatibility")[1])
check("Compatibility based on location", "location_preference" in svc.split("def calculate_compatibility")[1])
check("Compatibility based on trust score", "trust_score" in svc.split("def calculate_compatibility")[1])
check("Compatibility capped at 100", "min(100" in svc)
check("Compatibility floors at 0", "max(0" in svc)
check("Compatibility default 50 when no DB", "_db_available" in svc.split("def calculate_compatibility")[1][:100])

# SECTION 15: Data model
print("\n--- Data Model ---")
check("Dating mode is boolean", "boolean" in sql and "dating_mode_on" in sql)
check("Trust score defaults to 50", "trust_score int DEFAULT 50" in sql)
check("Safety badge defaults to false", "safety_badge boolean DEFAULT false" in sql)
check("Verification status defaults to unverified", "verification_status text DEFAULT 'unverified'" in sql)
check("Action type defaults to 'like'", "action_type text NOT NULL DEFAULT 'like'" in sql)
check("Match is_active defaults true", "is_active boolean DEFAULT true" in sql)
check("Match compatibility_score defaults 50", "compatibility_score int DEFAULT 50" in sql)
check("Report is_resolved defaults false", "is_resolved boolean DEFAULT false" in sql)
check("Preference show_me defaults true", "show_me boolean DEFAULT true" in sql)
check("Preference only_verified defaults false", "only_verified boolean DEFAULT false" in sql)
check("Preference interested_in defaults everyone", "interested_in text DEFAULT 'everyone'" in sql)
check("Preference min_age defaults 18", "min_age int DEFAULT 18" in sql)
check("Preference max_age defaults 99", "max_age int DEFAULT 99" in sql)
check("Preference max_distance_km defaults 100", "max_distance_km int DEFAULT 100" in sql)

# Summary
print("\n" + "=" * 60)
print(f"Results: {PASS}/{PASS + FAIL} passed, {FAIL} failed")
print("=" * 60)
if FAIL:
    print("\nFAILED:")
    for e in ERRORS:
        print(f"  - {e}")
    sys.exit(1)
