#!/bin/bash

echo "--- CHAIN PRODUCTION START COMMANDS ---"
echo ""
echo "1. Reload systemd:"
echo "   sudo systemctl daemon-reload"
echo ""
echo "2. Start Core Services (HTTP Mode):"
echo "   sudo systemctl enable chain"
echo "   sudo systemctl restart chain"
echo ""
echo "3. Start Realtime Services (Optional):"
echo "   sudo systemctl enable chain-realtime"
echo "   sudo systemctl restart chain-realtime"
echo ""
echo "4. Start Background Workers:"
echo "   sudo systemctl enable chain-worker"
echo "   sudo systemctl restart chain-worker"
echo ""
echo "5. Configure Nginx:"
echo "   sudo cp nginx/chain.conf.example /etc/nginx/sites-available/chain"
echo "   sudo ln -s /etc/nginx/sites-available/chain /etc/nginx/sites-enabled/"
echo "   sudo nginx -t && sudo systemctl reload nginx"
echo ""
echo "---------------------------------------"
