# Generated by Django 4.2.30 on 2026-04-21 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemPromoCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('body', models.TextField()),
                ('icon', models.CharField(blank=True, max_length=16)),
                ('cta_label', models.CharField(default='Open', max_length=80)),
                ('cta_url', models.CharField(blank=True, max_length=240)),
                ('placement', models.CharField(choices=[('homepage_feed', 'Homepage feed'), ('homepage_float', 'Homepage float'), ('support_dashboard', 'Support dashboard')], db_index=True, default='homepage_feed', max_length=32)),
                ('priority', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('audience', models.CharField(db_index=True, default='all', max_length=24)),
                ('dismissible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
                'indexes': [models.Index(fields=['placement', 'is_active', 'priority'], name='supportapp__placeme_4fa9e8_idx')],
            },
        ),
    ]
